### ISSUE TITLE
Error NoClassDefFoundError: org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by Shpalm4n** [sarxos/webcam-capture#103]
Hi sarxos, i'm  testing your library "com.github.sarxos.webcam"
I'm using Netbeans to develope my project. I have created a new project to test if the library function, i have add to the project the "webcam-capture-0.3.10-RC2.jar" file with "Add JAR/Folder.." function

And have created the Class TakePictureExample, by copying your expample in the file that i have downloaded.
But it dosn't work. It give me that error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
    at com.github.sarxos.webcam.Webcam.<clinit>(Webcam.java:38)
    at webcam.TakePictureExample.main(TakePictureExample.java:22)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 2 more
Java Result: 1
```

What i do wrong o what i have to do?
I'm using Windows 8 64-bit

Thanks

**Comment by GraceEmenike** [comment]
Hi, sarxos. I've been trying out your API for my school project i want to capture images and store them in a directory. but I've been getting similar errors with Shpalm4n like this:

Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.github.sarxos.webcam.Webcam.<clinit>(Webcam.java:101)
	at Sampled.TakePictureExample.main(TakePictureExample.java:26)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	... 2 more
Java Result: 1

I have donwnloaded the latest version of the library from the home page: webcam-capture-0.3.11-20150416.101652-7 , and it's still giving me the same error even if I import the library.
Please do I need OpenCv or JavaCv for this to work? 
Thanks.

**Comment by sarxos** [comment]
Hi @GraceEmenike,

Sorry for the late response. 

No you don't need OpenCV or any additional software installed on the PC (unless you want to use some specific driver like the ones for OpenCV, VLC, V4L, fswebcam, etc).

To fix the issue you are experiencing please download **zip** file from the project main page:

[webcam-capture-0.3.10-dist.zip](https://github.com/sarxos/webcam-capture/releases/download/webcam-capture-parent-0.3.10/webcam-capture-0.3.10-dist.zip)

When you unzip it, there is a ```libs``` directory inside which contains two JARs - one for SLF4J (this is the one which is missing so you see this error), and one for BridJ. Add both to your application classpath (together with webcam-capture JAR, of course) and you are free to go.

I'm sure your school project will be great :) Take care!

**Comment by GraceEmenike** [comment]
Thank you so much. it worked better now. I'd just like to ask if there is a way to take the snapshot without the system making any pop up indicator (like taking the picture in the background) and without any light indicator. Thanks.

**Comment by sarxos** [comment]
Hi Grace,

This is unfortunately not possible. The light diode indicator in webcam is
controlled by hardware and there is no software solution to disable it.

However, if you want user to be unaware of the app taking pictures, you can
start your application on system boot, so the user will not see diode
blinking because it will be turned on from the very beginning (the user may
think this is really normal, just yet another light) :P but this is a
method for rather not very clever PC users.

**Comment by GraceEmenike** [comment]
Thank you. You've been of so much help. The webcam capture is working fine
now.
I'd just let the light indicator issue pass. After all, I need only a few
seconds to get the snapshot I need from the trespassing user.
Great work there.
