### ISSUE TITLE
java.lang.RuntimeException: Library 'OpenIMAJGrabber' was not loaded successfully from file 

### ISSUE THREAD

**Issue by BuwanekaT** [sarxos/webcam-capture#116]
```
17:57:23.506 [main] INFO  com.github.sarxos.webcam.Webcam - WebcamDefaultDriver capture driver will be used
17:57:23.514 [webcam-discovery-service] DEBUG c.g.s.w.d.b.WebcamDefaultDriver - Searching devices
java.lang.RuntimeException: Library 'OpenIMAJGrabber' was not loaded successfully from file 'C:\Users\BUWANEKA\AppData\Local\Temp\BridJExtractedLibraries4538524950335047008\OpenIMAJGrabber.dll'
    at org.bridj.BridJ.getNativeLibrary(BridJ.java:952)
    at org.bridj.BridJ.getNativeLibrary(BridJ.java:931)
    at org.bridj.BridJ.getNativeLibrary(BridJ.java:543)
    at org.bridj.cpp.CPPRuntime.newCPPInstance(CPPRuntime.java:652)
    at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:858)
    at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:785)
    at org.bridj.CRuntime$CTypeInfo.initialize(CRuntime.java:249)
    at org.bridj.BridJ.initialize(BridJ.java:1000)
    at org.bridj.NativeObject.<init>(NativeObject.java:49)
    at org.bridj.StructObject.<init>(StructObject.java:44)
    at org.bridj.cpp.CPPObject.<init>(CPPObject.java:52)
    at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.<init>(OpenIMAJGrabber.java:64)
    at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.handle(WebcamDefaultDriver.java:56)
    at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:66)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
Exception in thread "main" com.github.sarxos.webcam.WebcamException: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
    at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:118)
    at com.github.sarxos.webcam.Webcam.getWebcams(Webcam.java:669)
# BridJ: LoadLibrary error when loading C:\Users\BUWANEKA\AppData\Local\Temp\BridJExtractedLibraries4538524950335047008\OpenIMAJGrabber.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\BUWANEKA\AppData\Local\Temp\BridJExtractedLibraries4538524950335047008\OpenIMAJGrabber.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\BUWANEKA\AppData\Local\Temp\BridJExtractedLibraries4538524950335047008\OpenIMAJGrabber.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\BUWANEKA\AppData\Local\Temp\BridJExtractedLibraries4538524950335047008\OpenIMAJGrabber.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\BUWANEKA\AppData\Local\Temp\BridJExtractedLibraries4538524950335047008\OpenIMAJGrabber.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\BUWANEKA\AppData\Local\Temp\BridJExtractedLibraries4538524950335047008\OpenIMAJGrabber.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\BUWANEKA\AppData\Local\Temp\BridJExtractedLibraries4538524950335047008\OpenIMAJGrabber.dll : The specified module could not be found.


    at com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:732)
# BridJ: LoadLibrary error when loading C:\Users\BUWANEKA\AppData\Local\Temp\BridJExtractedLibraries4538524950335047008\OpenIMAJGrabber.dll : The specified module could not be found.


# BridJ: LoadLibrary error when loading C:\Users\BUWANEKA\AppData\Local\Temp\BridJExtractedLibraries4538524950335047008\OpenIMAJGrabber.dll : The specified module could not be found.


    at com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:709)
# BridJ: LoadLibrary error when loading C:\Users\BUWANEKA\AppData\Local\Temp\BridJExtractedLibraries4538524950335047008\OpenIMAJGrabber.dll : The specified module could not be found.


    at com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:687)
# BridJ: LoadLibrary error when loading C:\Users\BUWANEKA\AppData\Local\Temp\BridJExtractedLibraries4538524950335047008\OpenIMAJGrabber.dll : The specified module could not be found.

    at example.DetectWebcamExample.main(DetectWebcamExample.java:8)

Caused by: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
    at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:252)
    at java.util.concurrent.FutureTask.get(FutureTask.java:111)
    at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:110)
    ... 5 more
Caused by: com.github.sarxos.webcam.WebcamException: Cannot execute task
    at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.process(WebcamProcessor.java:57)
    at com.github.sarxos.webcam.WebcamProcessor.process(WebcamProcessor.java:120)
    at com.github.sarxos.webcam.WebcamTask.process(WebcamTask.java:35)
    at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.newGrabber(WebcamDefaultDriver.java:46)
    at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver.getDevices(WebcamDefaultDriver.java:118)
    at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:35)
    at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:25)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.RuntimeException: Failed to allocate new instance of type class com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber
    at org.bridj.cpp.CPPRuntime.newCPPInstance(CPPRuntime.java:699)
    at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:858)
    at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:785)
    at org.bridj.CRuntime$CTypeInfo.initialize(CRuntime.java:249)
    at org.bridj.BridJ.initialize(BridJ.java:1000)
    at org.bridj.NativeObject.<init>(NativeObject.java:49)
    at org.bridj.StructObject.<init>(StructObject.java:44)
    at org.bridj.cpp.CPPObject.<init>(CPPObject.java:52)
    at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.<init>(OpenIMAJGrabber.java:64)
    at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.handle(WebcamDefaultDriver.java:56)
    at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:66)
    ... 3 more
Caused by: java.lang.RuntimeException: Library 'OpenIMAJGrabber' was not loaded successfully from file 'C:\Users\BUWANEKA\AppData\Local\Temp\BridJExtractedLibraries4538524950335047008\OpenIMAJGrabber.dll'
    at org.bridj.BridJ.getNativeLibrary(BridJ.java:952)
    at org.bridj.BridJ.getNativeLibrary(BridJ.java:931)
    at org.bridj.BridJ.getNativeLibrary(BridJ.java:543)
    at org.bridj.cpp.CPPRuntime.newCPPInstance(CPPRuntime.java:652)
    ... 13 more
Java Result: 1
BUILD SUCCESSFUL (total time: 0 seconds)
```

**Comment by nikhilmathewfrancis98** [comment]
Am also having the same error what to do
my os is Wndows 10
Webcam version : webcam-capture-0.3.13-20200330.202351-7.jar
Architecture : 64
java version: 1.8.0_51

**Comment by diveair** [comment]
I also get this issue after trying to git checkout the repo into Eclipse. I test the dev environment by exporting the unedited webcam-capture jar and then use it in an existing project (to test the dev environment before I edit the library) and I get the following printing to console *Note* the github jar file you can download for webcam-capture-0.3.12.jar works with my existing project just fine but upon Eclipse 09-2022 -> File -> Import -> Git -> Projects from Git (with smart import) -> Clone URI -> URI: https://github.com/sarxos/webcam-capture.git Host: github.com Repository path: /sarxos/webcam-capture.git Protocol: Https -> Branch: Master -> Select All -> Finish -> No visible errors -> then Eclipse -> Export -> Java -> JAR file -> Next -> webcam-capture_webcam-capture -> Finish and upon importing the jar into my working other project (in place of the one available at the repo) I get this error:


java.io.FileNotFoundException: Library 'OpenIMAJGrabber' was not found in path '[., C:/Program Files/Java/jre1.8.0_161/bin/server, C:/Program Files/Java/jre1.8.0_161/bin, C:/Program Files/Java/jre1.8.0_161/lib/amd64, C:\ProgramData\Oracle\Java\javapath, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0\, C:\Windows\System32\OpenSSH\, C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL, C:\Program Files\Intel\Intel(R) Management Engine Components\DAL, C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common, C:\WINDOWS\system32, C:\WINDOWS, C:\WINDOWS\System32\Wbem, C:\WINDOWS\System32\WindowsPowerShell\v1.0\, C:\WINDOWS\System32\OpenSSH\, C:\Program Files\Intel\WiFi\bin\, C:\Program Files\Common Files\Intel\WirelessCommon\, C:\Program Files (x86)\Schneider Electric\SoMachine Software\Tools\ConfigurationManager\, C:\Program Files (x86)\QuickTime\QTSystem\, C:\Program Files\Java\jdk1.8.0_161, C:\Program Files\Java\jdk1.8.0_161\bin, C:\Program Files\WorldPainter, C:\Program Files\TortoiseSVN\bin, C:\Program Files\dotnet\, C:\Users\PC\AppData\Local\Microsoft\WindowsApps, C:\Users\PC\Desktop\eclipse, C:\Program Files\Java\jre1.8.0_161\bin, C:\WINDOWS\system32, C:\WINDOWS, C:/Program Files/Java/jre1.8.0_161/bin/server, C:/Program Files/Java/jre1.8.0_161/bin, C:/Program Files/Java/jre1.8.0_161/lib/amd64, C:\ProgramData\Oracle\Java\javapath, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0\, C:\Windows\System32\OpenSSH\, C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL, C:\Program Files\Intel\Intel(R) Management Engine Components\DAL, C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common, C:\WINDOWS\system32, C:\WINDOWS, C:\WINDOWS\System32\Wbem, C:\WINDOWS\System32\WindowsPowerShell\v1.0\, C:\WINDOWS\System32\OpenSSH\, C:\Program Files\Intel\WiFi\bin\, C:\Program Files\Common Files\Intel\WirelessCommon\, C:\Program Files (x86)\Schneider Electric\SoMachine Software\Tools\ConfigurationManager\, C:\Program Files (x86)\QuickTime\QTSystem\, C:\Program Files\Java\jdk1.8.0_161, C:\Program Files\Java\jdk1.8.0_161\bin, C:\Program Files\WorldPainter, C:\Program Files\TortoiseSVN\bin, C:\Program Files\dotnet\, C:\Users\PC\AppData\Local\Microsoft\WindowsApps, C:\Users\PC\Desktop\eclipse, ., C:\Program Files\Java\jre1.8.0_161\bin, C:\Program Files\Java\jre1.8.0_161\bin]'
	at org.bridj.BridJ.getNativeLibrary(BridJ.java:1074)
	at org.bridj.BridJ.getNativeLibrary(BridJ.java:1049)
	at org.bridj.BridJ.getNativeLibrary(BridJ.java:602)
	at org.bridj.cpp.CPPRuntime.newCPPInstance(CPPRuntime.java:771)
	at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:1022)
	at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:904)
	at org.bridj.CRuntime$CTypeInfo.initialize(CRuntime.java:271)
	at org.bridj.BridJ.initialize(BridJ.java:1128)
	at org.bridj.NativeObject.<init>(NativeObject.java:50)
	at org.bridj.StructObject.<init>(StructObject.java:46)
	at org.bridj.cpp.CPPObject.<init>(CPPObject.java:55)
	at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.<init>(OpenIMAJGrabber.java:62)
	at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.handle(WebcamDefaultDriver.java:55)
	at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "main" com.github.sarxos.webcam.WebcamException: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
	at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:124)
	at com.github.sarxos.webcam.Webcam.getWebcams(Webcam.java:893)
	at com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:956)
	at com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:933)
	at com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:911)
	at guitest.Widgets.WebcamWidget.<init>(WebcamWidget.java:60)
	at guitest.MainApp.main(MainApp.java:75)
Caused by: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:116)
	... 6 more
Caused by: com.github.sarxos.webcam.WebcamException: Cannot execute task
	at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.process(WebcamProcessor.java:72)
	at com.github.sarxos.webcam.WebcamProcessor.process(WebcamProcessor.java:140)
	at com.github.sarxos.webcam.WebcamTask.process(WebcamTask.java:46)
	at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.newGrabber(WebcamDefaultDriver.java:45)
	at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver.getDevices(WebcamDefaultDriver.java:117)
	at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:36)
	at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:1)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Failed to allocate new instance of type class com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber
	at org.bridj.cpp.CPPRuntime.newCPPInstance(CPPRuntime.java:812)
	at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:1022)
	at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:904)
	at org.bridj.CRuntime$CTypeInfo.initialize(CRuntime.java:271)
	at org.bridj.BridJ.initialize(BridJ.java:1128)
	at org.bridj.NativeObject.<init>(NativeObject.java:50)
	at org.bridj.StructObject.<init>(StructObject.java:46)
	at org.bridj.cpp.CPPObject.<init>(CPPObject.java:55)
	at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.<init>(OpenIMAJGrabber.java:62)
	at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.handle(WebcamDefaultDriver.java:55)
	at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:81)
	... 3 more
Caused by: java.io.FileNotFoundException: Library 'OpenIMAJGrabber' was not found in path '[., C:/Program Files/Java/jre1.8.0_161/bin/server, C:/Program Files/Java/jre1.8.0_161/bin, C:/Program Files/Java/jre1.8.0_161/lib/amd64, C:\ProgramData\Oracle\Java\javapath, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0\, C:\Windows\System32\OpenSSH\, C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL, C:\Program Files\Intel\Intel(R) Management Engine Components\DAL, C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common, C:\WINDOWS\system32, C:\WINDOWS, C:\WINDOWS\System32\Wbem, C:\WINDOWS\System32\WindowsPowerShell\v1.0\, C:\WINDOWS\System32\OpenSSH\, C:\Program Files\Intel\WiFi\bin\, C:\Program Files\Common Files\Intel\WirelessCommon\, C:\Program Files (x86)\Schneider Electric\SoMachine Software\Tools\ConfigurationManager\, C:\Program Files (x86)\QuickTime\QTSystem\, C:\Program Files\Java\jdk1.8.0_161, C:\Program Files\Java\jdk1.8.0_161\bin, C:\Program Files\WorldPainter, C:\Program Files\TortoiseSVN\bin, C:\Program Files\dotnet\, C:\Users\PC\AppData\Local\Microsoft\WindowsApps, C:\Users\PC\Desktop\eclipse, C:\Program Files\Java\jre1.8.0_161\bin, C:\WINDOWS\system32, C:\WINDOWS, C:/Program Files/Java/jre1.8.0_161/bin/server, C:/Program Files/Java/jre1.8.0_161/bin, C:/Program Files/Java/jre1.8.0_161/lib/amd64, C:\ProgramData\Oracle\Java\javapath, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0\, C:\Windows\System32\OpenSSH\, C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL, C:\Program Files\Intel\Intel(R) Management Engine Components\DAL, C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common, C:\WINDOWS\system32, C:\WINDOWS, C:\WINDOWS\System32\Wbem, C:\WINDOWS\System32\WindowsPowerShell\v1.0\, C:\WINDOWS\System32\OpenSSH\, C:\Program Files\Intel\WiFi\bin\, C:\Program Files\Common Files\Intel\WirelessCommon\, C:\Program Files (x86)\Schneider Electric\SoMachine Software\Tools\ConfigurationManager\, C:\Program Files (x86)\QuickTime\QTSystem\, C:\Program Files\Java\jdk1.8.0_161, C:\Program Files\Java\jdk1.8.0_161\bin, C:\Program Files\WorldPainter, C:\Program Files\TortoiseSVN\bin, C:\Program Files\dotnet\, C:\Users\PC\AppData\Local\Microsoft\WindowsApps, C:\Users\PC\Desktop\eclipse, ., C:\Program Files\Java\jre1.8.0_161\bin, C:\Program Files\Java\jre1.8.0_161\bin]'
	at org.bridj.BridJ.getNativeLibrary(BridJ.java:1074)
	at org.bridj.BridJ.getNativeLibrary(BridJ.java:1049)
	at org.bridj.BridJ.getNativeLibrary(BridJ.java:602)
	at org.bridj.cpp.CPPRuntime.newCPPInstance(CPPRuntime.java:771)
	... 13 more

# BridJ: LoadLibrary error when loading OpenIMAJGrabber : The specified module could not be found.
