### ISSUE TITLE
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by AngelGz** [sarxos/webcam-capture#158]
Hi,

I am trying to use your library to capture images from a webcam. I have just downloaded the library and included the jar file in the library path of my netbeans project. The project compiles but when I try to run I get some errors. The code I am executing is the first example:

``` java
package capturador;

import com.github.sarxos.webcam.Webcam;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;

public class Capturador {

    public static void main(String[] args) {

            Webcam webcam = Webcam.getDefault();
            webcam.open();
            BufferedImage image = webcam.getImage();
            try{
           ImageIO.write(image, "PNG", new File("test.png"));}
            catch(Exception e){
            System.out.println(e.toString());}
    }

}
```

And what I get then trying to run it is:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
    at com.github.sarxos.webcam.Webcam.<clinit>(Webcam.java:38)
    at capturador.Capturador.main(Capturador.java:27)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 2 more
Java Result: 1
BUILD SUCCESSFUL (total time: 0 seconds)
```

What have I done wrong? 

Thank you for is amazing library!
Angel.

**Comment by rrbadam** [comment]
webcam-capture-0.3.3.jar. Place this jar in your classpath

**Comment by ssrivastava123** [comment]
Cannot invoke "com.github.sarxos.webcam.Webcam.getName()" because "selectedWebcam" is null facing this exception Mac OS using SpringBoot and webcam capture 3.12 lib maven
