### ISSUE TITLE
Webcam CyberLink Webcam Splitter 0 has already been locked

### ISSUE THREAD

**Issue by ajay154** [sarxos/webcam-capture#174]
when I executed DetectMotionExample.java it give me error::

``` plain
Exception in thread "main" com.github.sarxos.webcam.WebcamLockException: Webcam CyberLink Webcam Splitter 0 has already been locked
    at com.github.sarxos.webcam.WebcamLock.lock(WebcamLock.java:224)
    at com.github.sarxos.webcam.Webcam.open(Webcam.java:181)
    at com.github.sarxos.webcam.Webcam.open(Webcam.java:147)
    at com.github.sarxos.webcam.WebcamMotionDetector.start(WebcamMotionDetector.java:186)
    at DetectMotionExample.<init>(DetectMotionExample.java:22)
    at DetectMotionExample.main(DetectMotionExample.java:31)
```

**Comment by UrviT** [comment]
How to change the version through maven dependency?
Currently: 	<version>0.3.10</version>
How to get RC6 here?
