### ISSUE TITLE
Caused by: com.github.sarxos.webcam.WebcamException: Content Type header is missing

### ISSUE THREAD

**Issue by laxmikants110688** [sarxos/webcam-capture#216]
how to set content type header ? please help me
Here is the code .

``` java
public class Ipcam {

    /**
     * @param args the command line arguments
     */
    static{
    Webcam.setDriver(new IpCamDriver());
    }
    public static void main(String[] args) throws MalformedURLException, IOException, Exception {
        //ExamplePolymorphism.main(args);
        //IpCamDevice o = new IpCamDevice(), null, IpCamMode.PULL)
        IpCamDevice register = IpCamDeviceRegistry.register(new IpCamDevice("MJPEG", "http://192.168.1.2:8080/photo.jpg", IpCamMode.PULL));


        Webcam.setHandleTermSignal(true);
    WebcamPanel panel = new WebcamPanel(Webcam.getWebcams().get(0));
    panel.setFPSLimit(0.5);

    JFrame f = new JFrame("Live Views From Lignano Beach");
    f.setSize(400,400);
    f.add(panel);
    JButton snap = new JButton("Snap Me!");
    panel.add(snap);
    snap.addActionListener(new ActionListener() {     
```

---

run:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" com.github.sarxos.webcam.WebcamException: Cannot download image
    at com.github.sarxos.webcam.ds.ipcam.IpCamDevice.getImagePullMode(IpCamDevice.java:387)
    at com.github.sarxos.webcam.ds.ipcam.IpCamDevice.getImage(IpCamDevice.java:302)
    at com.github.sarxos.webcam.ds.ipcam.IpCamDevice.getResolutions(IpCamDevice.java:260)
    at com.github.sarxos.webcam.ds.ipcam.IpCamDevice.getResolution(IpCamDevice.java:283)
    at com.github.sarxos.webcam.Webcam.getViewSize(Webcam.java:403)
    at com.github.sarxos.webcam.WebcamPanel.<init>(WebcamPanel.java:505)
    at com.github.sarxos.webcam.WebcamPanel.<init>(WebcamPanel.java:476)
    at com.github.sarxos.webcam.WebcamPanel.<init>(WebcamPanel.java:465)
    at ipcam.Ipcam.main(Ipcam.java:71)
Caused by: com.github.sarxos.webcam.WebcamException: Content Type header is missing
    at com.github.sarxos.webcam.ds.ipcam.IpCamDevice.getImagePullMode(IpCamDevice.java:363
```

getting this exception and don't really know how to set content type .

**Comment by 10sw33** [comment]
i was also facing same problem and after all these suggestion i stuck here because this is what my output came. what todo further ..
![err](https://cloud.githubusercontent.com/assets/10362378/5772140/3d430c72-9d6e-11e4-9b85-4716d416f3ac.png)

**Comment by sarxos** [comment]
@10sw33, you are getting HTTP 404 Not Found which means that URL you are trying to use does not points to any image.

```plain
http://[server]:[port]/mjpeg/videostream.mjpeg
```

I would start from checking why this URL is incorrect and then by using correct one, which returns HTTP 200 Ok.

This is different issue than described by @laxmikants110688 (which was invalid authorization).
