### ISSUE TITLE
Problem in connecting to webcam using JavaCv Driver

### ISSUE THREAD

**Issue by rakeshbhatt10** [sarxos/webcam-capture#238]
HI Sarxos,

I am currently trying to use your JavaCv driver i downloaded your JavaCv Driver project and and setup lib folder including JavaCv 0.8 jars, webcam-capture-0.3.10-RC7.jar  add them into classpath. But while i run it it is giving me exception

 stacktrace is below:

``` plain
Exception in thread "main" com.github.sarxos.webcam.WebcamException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: no jnivideoInputLib in java.library.path
    at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:124)
    at com.github.sarxos.webcam.Webcam.getWebcams(Webcam.java:796)
    at com.github.sarxos.webcam.Webcam.getWebcams(Webcam.java:769)
    at com.github.sarxos.webcam.Webcam.getWebcams(Webcam.java:749)
    at com.test.JavaCvDriverExample.main(JavaCvDriverExample.java:17)
Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: no jnivideoInputLib in java.library.path
    at java.util.concurrent.FutureTask$Sync.innerGet(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:116)
    ... 4 more
Caused by: java.lang.UnsatisfiedLinkError: no jnivideoInputLib in java.library.path
    at java.lang.ClassLoader.loadLibrary(Unknown Source)
    at java.lang.Runtime.loadLibrary0(Unknown Source)
    at java.lang.System.loadLibrary(Unknown Source)
    at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:524)
    at org.bytedeco.javacpp.Loader.load(Loader.java:399)
    at org.bytedeco.javacpp.Loader.load(Loader.java:353)
    at org.bytedeco.javacpp.videoInputLib.<clinit>(videoInputLib.java:10)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at org.bytedeco.javacpp.Loader.load(Loader.java:374)
    at org.bytedeco.javacpp.Loader.load(Loader.java:353)
    at org.bytedeco.javacpp.videoInputLib$videoInput.<clinit>(videoInputLib.java:330)
    at com.github.sarxos.webcam.ds.javacv.JavaCvDriver.getDevicesWindows(JavaCvDriver.java:29)
    at com.github.sarxos.webcam.ds.javacv.JavaCvDriver.getDevices(JavaCvDriver.java:54)
    at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:36)
    at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:26)
    at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsatisfiedLinkError: no uuid in java.library.path
    at java.lang.ClassLoader.loadLibrary(Unknown Source)
    at java.lang.Runtime.loadLibrary0(Unknown Source)
    at java.lang.System.loadLibrary(Unknown Source)
    at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:524)
    at org.bytedeco.javacpp.Loader.load(Loader.java:390)
```

While the error is related to 

```
java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError:
```

But when i run JavaCV samples it runs fine. So if this is the linking problem JavaCv examples would not run either

I am currently using OpenCV 2.4.9  and JavaCv 0.8. 

I also want to ask one more thing 

 You had written title of frame in example of 
JavaCv Driver as ":LTI-CIVIL Webcam Capture Driver Example" which is also i didn't understood if we use JavaCV it will use OpencvFFMPEGDriver or FFMPEGDriver for camera connectivity. But lit-civil will require different set of c++ header files please clarify me i am a newbie into this:

Thanks is advance
Rakesh Bhatt

**Comment by qweasdzxcpoi** [comment]
@sarxos 
How to add opencv bin to PATH

ex: my path to bin is /home/chandansr/opencv-2.4.9/build/bin
