### ISSUE TITLE
reconnect when the connection drops  

### ISSUE THREAD

**Issue by henriquem** [sarxos/webcam-capture#271]
I have opened this issue in May/2014 - How I reconnect the Webcam MJPEG #214 
But I have still an doubt when I disconnected for example:
not release not Exception if is disconnect or connect.
For example I acess the camera ip online - ok 
when take out cable, not throw Exception 

Try this example:
MODE.PULL 
"http://ce3014.myfoscam.org:20054/snapshot.cgi?user=user&pwd=user&rate=0",  

But if my computer is disconnect, and I start an camera ip try to an access
So, throw Exception - OK
following bellow:

``` plain
       ERROR com.github.sarxos.webcam.WebcamExceptionHandler:32 - Exception in thread motion-detector-1
com.github.sarxos.webcam.WebcamException: Cannot download image
    at com.github.sarxos.webcam.ds.ipcam.IpCamDevice.getImagePullMode(IpCamDevice.java:404)
    at com.github.sarxos.webcam.ds.ipcam.IpCamDevice.getImage(IpCamDevice.java:319)
    at com.github.sarxos.webcam.ds.cgt.WebcamGetImageTask.handle(WebcamGetImageTask.java:43)
    at com.github.sarxos.webcam.WebcamTask.process(WebcamTask.java:48)
    at com.github.sarxos.webcam.ds.cgt.WebcamGetImageTask.getImage(WebcamGetImageTask.java:26)
    at com.github.sarxos.webcam.Webcam.getImage(Webcam.java:630)
    at com.github.sarxos.webcam.WebcamMotionDetector.detect(WebcamMotionDetector.java:279)
    at        com.github.sarxos.webcam.WebcamMotionDetector$Runner.run(WebcamMotionDetector.java:87)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
```

While this Exception is throwing always, I connect the cable network ( camming on the Internet again)
Another error occured:

``` plain
       Caused by: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
    at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:397)
    at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:126)
    at org.apache.http.conn.ssl.SSLSocketFactory.createLayeredSocket(SSLSocketFactory.java:628)
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.updateSecureConnection(DefaultClientConnectionOperator.java:232)
    at org.apache.http.impl.conn.ManagedClientConnectionImpl.layerProtocol(ManagedClientConnectionImpl.java:401)
    at        org.apache.http.impl.client.DefaultRequestDirector.establishRoute(DefaultRequestDirector.java:842)
    at               org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:649)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:480)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
    at com.github.sarxos.webcam.ds.ipcam.IpCamDevice.getImagePullMode(IpCamDevice.java:378)
```

How I can handler when the occured disconnection/ connection ?
I already use the version with improved #214  but I dont know How I can capture this error in my class 
used like bellow and reconnect again!

``` java
       public class CameraService extends Thread implements WebcamMotionListener{
               private Webcam camera;
                private WebcamMotionDetector detectorMoviment;
               public CameraService(Webcam camera){
                        detectorMoviment = new WebcamMotionDetector(camera);
                    detectorMoviment.setInterval(500); // one check per 500 ms
                    detectorMoviment.setInertia(1000);
                    detectorMoviment.addMotionListener(this);
               }

              @Override
           public void motionDetected(WebcamMotionEvent event) {
               try  {
                        WebcamMotionDetector motion=(WebcamMotionDetector) event.getSource();
                        IplImage imageCaptured = IplImage.createFrom(motion.getWebcam().getImage());
                       }catch(Exception e){
                        e.printStackTrace();
               }
              }
```

Please could you clean my doubt ?

Thanks
Henrique

**Comment by sarxos** [comment]
Hi @henriquem,

Usually it's enough to close and open webcam again.

The second error comes from the problem with the SSL certificate which seems to be invalid (e.g. expired, with wrong name, or at least self-signed). Are you using https to access your camera?

**Comment by sarxos** [comment]
@henriquem, any news on this?

**Comment by henriquem** [comment]
the second error that make sense, SSL certificate....
The unique problem is reconnect automatic, But I understood that is good 
candidate for an new feature.
Thks a lot!

**Comment by sarxos** [comment]
Yes, it's a good candidate. I will mark this as _enhancement_ and keep open until it's done.
