### ISSUE TITLE
usb c170 logitech wecam detection when piugged in and pludded out for conferencing project

### ISSUE THREAD

**Issue by bablunani** [sarxos/webcam-capture#317]
Hi sarxos,
I'm using WebcamDetectListnerExample to detect when ever my cam is plugged to usb port
I'm getting the following error,when i do twice plug in and plug out

```plain
Auto open method= true
Exception in thread "Thread-5"
com.github.sarxos.webcam.WebcamLockException: Webcam Webcam C170 /dev/video0 has already been locked
	at com.github.sarxos.webcam.WebcamLock.lock(WebcamLock.java:224)
	at vc.WebcamImage.<init>(WebcamImage.java:39)
	at vc.WebcamDiscoveryListenerExample.run(WebcamDiscoveryListenerExample.java:54)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sarxos** [comment]
Hi @bablunani,

Thank you for the report.

This duplicates #302. All activities related to this issue will be tracked there.
