### ISSUE TITLE
JProfiler profiling crash webcam api

### ISSUE THREAD

**Issue by jduke32** [sarxos/webcam-capture#344]
Hello , when i tried to use jprofile to optimize software.
Webcam.getDefault(); throws exception  like below:

```
D:\Tools\JDK\1.8\x64\bin\java -agentpath:D:\JProfiler8\bin\windows-x64\jprofilerti.dll=port=34655 -Djprofiler.64bit=true -Djava.library.path=C:\Users\Kadir\IdeaProjects\WebcamTransmitter\nativeLib\windows\x64 -Didea.launcher.port=7532 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA 14.1.3\bin" -Dfile.encoding=windows-1252 -classpath "D:\Tools\JDK\1.8\x64\jre\lib\charsets.jar;D:\Tools\JDK\1.8\x64\jre\lib\deploy.jar;D:\Tools\JDK\1.8\x64\jre\lib\javaws.jar;D:\Tools\JDK\1.8\x64\jre\lib\jce.jar;D:\Tools\JDK\1.8\x64\jre\lib\jfr.jar;D:\Tools\JDK\1.8\x64\jre\lib\jfxswt.jar;D:\Tools\JDK\1.8\x64\jre\lib\jsse.jar;D:\Tools\JDK\1.8\x64\jre\lib\management-agent.jar;D:\Tools\JDK\1.8\x64\jre\lib\plugin.jar;D:\Tools\JDK\1.8\x64\jre\lib\resources.jar;D:\Tools\JDK\1.8\x64\jre\lib\rt.jar;D:\Tools\JDK\1.8\x64\jre\lib\ext\access-bridge-64.jar;D:\Tools\JDK\1.8\x64\jre\lib\ext\cldrdata.jar;D:\Tools\JDK\1.8\x64\jre\lib\ext\dnsns.jar;D:\Tools\JDK\1.8\x64\jre\lib\ext\jaccess.jar;D:\Tools\JDK\1.8\x64\jre\lib\ext\jfxrt.jar;D:\Tools\JDK\1.8\x64\jre\lib\ext\localedata.jar;D:\Tools\JDK\1.8\x64\jre\lib\ext\nashorn.jar;D:\Tools\JDK\1.8\x64\jre\lib\ext\sunec.jar;D:\Tools\JDK\1.8\x64\jre\lib\ext\sunjce_provider.jar;D:\Tools\JDK\1.8\x64\jre\lib\ext\sunmscapi.jar;D:\Tools\JDK\1.8\x64\jre\lib\ext\sunpkcs11.jar;D:\Tools\JDK\1.8\x64\jre\lib\ext\zipfs.jar;C:\Users\Kadir\IdeaProjects\WebcamTransmitter\target\classes;C:\Users\Kadir\.m2\repository\com\github\sarxos\webcam-capture\0.3.10\webcam-capture-0.3.10.jar;C:\Users\Kadir\.m2\repository\com\nativelibs4java\bridj\0.6.2\bridj-0.6.2.jar;C:\Users\Kadir\.m2\repository\org\bytedeco\javacpp\0.11\javacpp-0.11.jar;C:\Users\Kadir\.m2\repository\org\bytedeco\javacpp-presets\ffmpeg\2.6.1-1.0-SNAPSHOT\ffmpeg-2.6.1-1.0-SNAPSHOT.jar;C:\Users\Kadir\.m2\repository\org\slf4j\slf4j-log4j12\1.5.5\slf4j-log4j12-1.5.5.jar;C:\Users\Kadir\.m2\repository\log4j\log4j\1.2.14\log4j-1.2.14.jar;C:\Users\Kadir\.m2\repository\org\slf4j\slf4j-api\1.5.5\slf4j-api-1.5.5.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA 14.1.3\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain WebcamCapture
JProfiler> Protocol version 41
JProfiler> Using JVMTI
JProfiler> JVMTI version 1.1 detected.
JProfiler> 64-bit library
JProfiler> Listening on port: 34655.
JProfiler> Instrumenting native methods.
JProfiler> Can retransform classes.
JProfiler> Can retransform any class.
JProfiler> Native library initialized
JProfiler> VM initialized
JProfiler> Waiting for a connection from the JProfiler GUI ...
JProfiler> Using dynamic instrumentation
JProfiler> Time measurement: elapsed time
JProfiler> CPU profiling enabled
log4j:WARN No appenders could be found for logger (com.github.sarxos.webcam.Webcam).
log4j:WARN Please initialize the log4j system properly.
Exception in thread "Thread-0" com.github.sarxos.webcam.WebcamException: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
	at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:124)
	at com.github.sarxos.webcam.Webcam.getWebcams(Webcam.java:816)
	at com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:879)
	at com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:856)
	at com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:834)
	at WebcamCapture.restart(WebcamCapture.java:150)
	at WebcamCapture.run2(WebcamCapture.java:206)
	at WebcamCapture.run(WebcamCapture.java:128)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:116)
	... 8 more
Caused by: com.github.sarxos.webcam.WebcamException: Cannot execute task
	at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.process(WebcamProcessor.java:72)
	at com.github.sarxos.webcam.WebcamProcessor.process(WebcamProcessor.java:140)
	at com.github.sarxos.webcam.WebcamTask.process(WebcamTask.java:46)
	at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$GetDevicesTask.getDevices(WebcamDefaultDriver.java:80)
	at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver.getDevices(WebcamDefaultDriver.java:125)
	at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:36)
	at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
Caused by: java.lang.UnsatisfiedLinkError: com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.__ejt_nmp_getVideoDevices()Lorg/bridj/Pointer;
	at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.__ejt_nmp_getVideoDevices(Native Method)
	at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.getVideoDevices(OpenIMAJGrabber.java)
	at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$GetDevicesTask.handle(WebcamDefaultDriver.java:94)
	at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:81)
	... 3 more

Process finished with exit code 0
```

**Comment by sarxos** [comment]
Hi @jduke32,

This is because JProfiler incorrectly instrumented ```OpenIMAJGrabber``` class.

https://github.com/sarxos/webcam-capture/blob/master/webcam-capture/src/main/java/com/github/sarxos/webcam/ds/buildin/natives/OpenIMAJGrabber.java

Let me clarify the above - the ```OpenIMAJGrabber``` is a class which expose native methods. As you probably know, the native methods names must exactly match the names from DLL file which is dynamically linked. In your case I see JProfiler instrumenting this class to create native method with name ```__ejt_nmp_getVideoDevices()``` and because there is no such method in DLL file Java throws ```UnsatisfiedLinkError```.

I suggest to dig into the JProfiler documentation to find out how to disable specific classes instrumentation or how to at least configure it so it does not spoils the rename. Unfortunately I'm not familiar with this tool and cannot give you ready to use solution, however this issue duplicates #80 where I included some other ideas (e.g. use of JVisualVM instead of JProfiler). You can take a look at it as well.
