### ISSUE TITLE
Compiling with excelsior jet + single jar  throws exception

### ISSUE THREAD

**Issue by jduke32** [sarxos/webcam-capture#346]
Hi , when i tried to compile Webcam Capture API maven-assembly-plugin single jar.
Single jar works fine but when i tried to compile with Excelsior JET , i got error : 
JET RT initialized
Class WebcamCapture found
log4j:WARN No appenders could be found for logger (com.github.sarxos.webcam.Webcam).
log4j:WARN Please initialize the log4j system properly.
Exception in thread "Thread-0" com.github.sarxos.webcam.WebcamException: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
        at Unknown.<unknown>(Unknown Source)
        at Unknown.<unknown>(Unknown Source)
        at Unknown.<unknown>(Unknown Source)
        at Unknown.<unknown>(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
        ... 4 more
Caused by: com.github.sarxos.webcam.WebcamException: Cannot execute task
        ... 4 more
Caused by: java.lang.ExceptionInInitializerError
        ... 4 more
Caused by: java.lang.RuntimeException: Failed to register class Unknown
        ... 4 more
Caused by: java.lang.ClassNotFoundException: Unknown
        ... 4 more

**Comment by sarxos** [comment]
Hi @jduke32,

The ```java.lang.ClassNotFoundException: Unknown``` points me to the thinking that some class is missing, but since Excelsior cuts out all useful informations it may be almost impossible to find out which one is missing. 

Does it have some capabilities to disable obfuscation so we can see stack trace or "real" class name instead of ```Unknown```?
