### ISSUE TITLE
Using Eclipse or starting via java -jar the WebCamViewerExample.java blocks when closing via menu

### ISSUE THREAD

**Issue by OLFDB** [sarxos/webcam-capture#381]
Hi,

I started using the WebCamViewerExample.java in an Eclipse project.
When I export it as runnable jar and start it with java -jar, or I start it in Eclipse and use the Menu to quit the application it blocks.

Here is the thread dump:

2015-08-15 16:55:40
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.31-b07 mixed mode):

"shutdown-hook-1" #29 daemon prio=6 os_prio=31 tid=0x00007ffab4200800 nid=0x19403 waiting on condition [0x0000000140925000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000716f4d408> (a java.util.concurrent.SynchronousQueue$TransferQueue)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.SynchronousQueue$TransferQueue.awaitFulfill(SynchronousQueue.java:762)
	at java.util.concurrent.SynchronousQueue$TransferQueue.transfer(SynchronousQueue.java:695)
	at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
	at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.process(WebcamProcessor.java:70)
	at com.github.sarxos.webcam.WebcamProcessor.process(WebcamProcessor.java:140)
	at com.github.sarxos.webcam.WebcamTask.process(WebcamTask.java:46)
	at com.github.sarxos.webcam.ds.cgt.WebcamDisposeTask.dispose(WebcamDisposeTask.java:20)
	at com.github.sarxos.webcam.Webcam.dispose(Webcam.java:426)
	at com.github.sarxos.webcam.WebcamShutdownHook.run(WebcamShutdownHook.java:44)

"notificator-[Microsoft® LifeCam HD-5001 0x14a40000045e076e]" #31 daemon prio=6 os_prio=31 tid=0x00007ffabc26c000 nid=0x1742f waiting on condition [0x0000000138fed000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000717c14018> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"frames-refresher-[0x14a40000045e076e]" #28 daemon prio=6 os_prio=31 tid=0x00007ffab5d41000 nid=0x18e5b waiting on condition [0x000000013ca75000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000716f4cfa0> (a java.util.concurrent.SynchronousQueue$TransferQueue)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.SynchronousQueue$TransferQueue.awaitFulfill(SynchronousQueue.java:762)
	at java.util.concurrent.SynchronousQueue$TransferQueue.transfer(SynchronousQueue.java:695)
	at java.util.concurrent.SynchronousQueue.put(SynchronousQueue.java:877)
	at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.process(WebcamProcessor.java:68)
	at com.github.sarxos.webcam.WebcamProcessor.process(WebcamProcessor.java:140)
	at com.github.sarxos.webcam.WebcamTask.process(WebcamTask.java:46)
	at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDevice$NextFrameTask.nextFrame(WebcamDefaultDevice.java:60)
	at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDevice.updateFrameBuffer(WebcamDefaultDevice.java:451)
	at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDevice.run(WebcamDefaultDevice.java:480)
	at java.lang.Thread.run(Thread.java:745)

"webcam-lock-[Microsoft® LifeCam HD-5001 0x14a40000045e076e]" #27 daemon prio=6 os_prio=31 tid=0x00007ffab42f8000 nid=0x17603 waiting on condition [0x00000001390f0000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at com.github.sarxos.webcam.WebcamLock$LockUpdater.run(WebcamLock.java:60)

"webcam-discovery-service" #23 daemon prio=6 os_prio=31 tid=0x00007ffab48e6000 nid=0xe40b waiting on condition [0x0000000136a1d000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000716f4cfa0> (a java.util.concurrent.SynchronousQueue$TransferQueue)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.SynchronousQueue$TransferQueue.awaitFulfill(SynchronousQueue.java:762)
	at java.util.concurrent.SynchronousQueue$TransferQueue.transfer(SynchronousQueue.java:695)
	at java.util.concurrent.SynchronousQueue.put(SynchronousQueue.java:877)
	at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.process(WebcamProcessor.java:68)
	at com.github.sarxos.webcam.WebcamProcessor.process(WebcamProcessor.java:140)
	at com.github.sarxos.webcam.WebcamTask.process(WebcamTask.java:46)
	at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$GetDevicesTask.getDevices(WebcamDefaultDriver.java:80)
	at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver.getDevices(WebcamDefaultDriver.java:125)
	at com.github.sarxos.webcam.WebcamDiscoveryService.scan(WebcamDiscoveryService.java:156)
	at com.github.sarxos.webcam.WebcamDiscoveryService.run(WebcamDiscoveryService.java:265)
	at java.lang.Thread.run(Thread.java:745)

"atomic-processor-1" #21 daemon prio=6 os_prio=31 tid=0x00007ffab70e0000 nid=0xe607 runnable [0x0000000136b20000]
   java.lang.Thread.State: RUNNABLE
	at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.stopSession(Native Method)
	at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDevice.close(WebcamDefaultDevice.java:391)
	at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDevice.dispose(WebcamDefaultDevice.java:403)
	at com.github.sarxos.webcam.ds.cgt.WebcamDisposeTask.handle(WebcamDisposeTask.java:25)
	at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"DestroyJavaVM" #18 prio=5 os_prio=31 tid=0x00007ffab400b000 nid=0x1303 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"AWT-EventQueue-0" #17 prio=6 os_prio=31 tid=0x00007ffab4856000 nid=0xdf03 waiting on condition [0x00000001367f0000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007156e5b10> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.awt.EventQueue.getNextEvent(EventQueue.java:547)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:170)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

"Java2D Disposer" #16 daemon prio=10 os_prio=31 tid=0x00007ffab486e800 nid=0xdd17 in Object.wait() [0x00000001361ee000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000007157c1a30> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:142)
	- locked <0x00000007157c1a30> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:158)
	at sun.java2d.Disposer.run(Disposer.java:148)
	at java.lang.Thread.run(Thread.java:745)

"Java2D Queue Flusher" #15 daemon prio=10 os_prio=31 tid=0x00007ffab40eb000 nid=0xd707 in Object.wait() [0x0000000135867000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at sun.java2d.opengl.OGLRenderQueue$QueueFlusher.run(OGLRenderQueue.java:203)
	- locked <0x00000007157be478> (a sun.java2d.opengl.OGLRenderQueue$QueueFlusher)

"AWT-Shutdown" #14 prio=5 os_prio=31 tid=0x00007ffab58d7000 nid=0x7d13 in Object.wait() [0x0000000132c56000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000715fc81e0> (a java.lang.Object)
	at java.lang.Object.wait(Object.java:502)
	at sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:295)
	- locked <0x0000000715fc81e0> (a java.lang.Object)
	at java.lang.Thread.run(Thread.java:745)

"AppKit Thread" #13 daemon prio=5 os_prio=31 tid=0x00007ffab40df800 nid=0x713 in Object.wait() [0x00007fff58299000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000717c1dc80> (a com.github.sarxos.webcam.WebcamShutdownHook)
	at java.lang.Thread.join(Thread.java:1245)
	- locked <0x0000000717c1dc80> (a com.github.sarxos.webcam.WebcamShutdownHook)
	at java.lang.Thread.join(Thread.java:1319)
	at java.lang.ApplicationShutdownHooks.runHooks(ApplicationShutdownHooks.java:106)
	at java.lang.ApplicationShutdownHooks$1.run(ApplicationShutdownHooks.java:46)
	at java.lang.Shutdown.runHooks(Shutdown.java:123)
	at java.lang.Shutdown.sequence(Shutdown.java:167)
	at java.lang.Shutdown.exit(Shutdown.java:212)
	- locked <0x00000007172c3b78> (a java.lang.Class for java.lang.Shutdown)
	at java.lang.Runtime.exit(Runtime.java:109)
	at java.lang.System.exit(System.java:968)
	at com.apple.eawt._AppEventHandler.performQuit(_AppEventHandler.java:145)
	- locked <0x0000000715fc8d60> (a com.apple.eawt._AppEventHandler)
	at com.apple.eawt.QuitResponse.performQuit(QuitResponse.java:51)
	at com.apple.eawt._AppEventHandler$_QuitDispatcher.performDefaultAction(_AppEventHandler.java:390)
	at com.apple.eawt._AppEventHandler$_AppEventDispatcher.dispatch(_AppEventHandler.java:512)
	at com.apple.eawt._AppEventHandler.handleNativeNotification(_AppEventHandler.java:202)

"Service Thread" #12 daemon prio=9 os_prio=31 tid=0x00007ffab5817800 nid=0x5703 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #11 daemon prio=9 os_prio=31 tid=0x00007ffab681c800 nid=0x5503 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #10 daemon prio=9 os_prio=31 tid=0x00007ffab6813800 nid=0x5303 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #9 daemon prio=9 os_prio=31 tid=0x00007ffab7803000 nid=0x5103 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #8 daemon prio=9 os_prio=31 tid=0x00007ffab6809000 nid=0x4f03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"JDWP Command Reader" #7 daemon prio=10 os_prio=31 tid=0x00007ffab7801000 nid=0x4d03 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"JDWP Event Helper Thread" #6 daemon prio=10 os_prio=31 tid=0x00007ffab480e000 nid=0x4b03 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"JDWP Transport Listener: dt_socket" #5 daemon prio=10 os_prio=31 tid=0x00007ffab4808000 nid=0x4903 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007ffab5814000 nid=0x3c17 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007ffab6807800 nid=0x3503 in Object.wait() [0x000000012ecb8000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000007155862f8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:142)
	- locked <0x00000007155862f8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:158)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007ffab4807800 nid=0x3303 in Object.wait() [0x000000012ebb5000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000715585d68> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)
	- locked <0x0000000715585d68> (a java.lang.ref.Reference$Lock)

"VM Thread" os_prio=31 tid=0x00007ffab4805000 nid=0x3103 runnable 

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x00007ffab4016000 nid=0x2103 runnable 

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x00007ffab4017000 nid=0x2303 runnable 

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x00007ffab4017800 nid=0x2503 runnable 

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x00007ffab4018000 nid=0x2703 runnable 

"GC task thread#4 (ParallelGC)" os_prio=31 tid=0x00007ffab4018800 nid=0x2903 runnable 

"GC task thread#5 (ParallelGC)" os_prio=31 tid=0x00007ffab4019800 nid=0x2b03 runnable 

"GC task thread#6 (ParallelGC)" os_prio=31 tid=0x00007ffab401a000 nid=0x2d03 runnable 

"GC task thread#7 (ParallelGC)" os_prio=31 tid=0x00007ffab401a800 nid=0x2f03 runnable 

"VM Periodic Task Thread" os_prio=31 tid=0x00007ffab5816000 nid=0x5903 waiting on condition 

JNI global references: 3152

Heap
 PSYoungGen      total 153088K, used 103690K [0x0000000715580000, 0x0000000720000000, 0x00000007c0000000)
  eden space 131584K, 78% used [0x0000000715580000,0x000000071bac2978,0x000000071d600000)
  from space 21504K, 0% used [0x000000071eb00000,0x000000071eb00000,0x0000000720000000)
  to   space 21504K, 0% used [0x000000071d600000,0x000000071d600000,0x000000071eb00000)
 ParOldGen       total 349696K, used 0K [0x00000005c0000000, 0x00000005d5580000, 0x0000000715580000)
  object space 349696K, 0% used [0x00000005c0000000,0x00000005c0000000,0x00000005d5580000)
 Metaspace       used 14470K, capacity 14670K, committed 15104K, reserved 1062912K
  class space    used 1865K, capacity 1931K, committed 2048K, reserved 1048576K

**Comment by sarxos** [comment]
Hi, thank you for the report. Can you please give me more details on your operating system version and architecture.

**Comment by sarxos** [comment]
I see this thread is blocking the others:

```plain
"atomic-processor-1" #21 daemon prio=6 os_prio=31 tid=0x00007ffab70e0000 nid=0xe607 runnable [0x0000000136b20000]
   java.lang.Thread.State: RUNNABLE
    at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.stopSession(Native Method)
    at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDevice.close(WebcamDefaultDevice.java:391)
    at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDevice.dispose(WebcamDefaultDevice.java:403)
    at com.github.sarxos.webcam.ds.cgt.WebcamDisposeTask.handle(WebcamDisposeTask.java:25)
    at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:81)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

This is known issue on Apples. Are you using one?

**Comment by OLFDB** [comment]
Yes. Any chance to fix or workaround this?

Regards

Olaf
