### ISSUE TITLE
java.lang.NoClassDefFoundError: ch/qos/logback/core/Context

### ISSUE THREAD

**Issue by MarcJose** [sarxos/webcam-capture#447]
Hello,
I am using Maven to ingreate this library but when I build with _`mvn clean compile assembly:single`_ and run the generated jar-file I get:
```
java.lang.ClassCastException: org.slf4j.impl.SimpleLoggerFactory cannot be cast to ch.qos.logback.classic.LoggerContext
        at com.github.sarxos.webcam.log.WebcamLogConfigurator.configure(WebcamLogConfigurator.java:44)
        at com.github.sarxos.webcam.log.WebcamLogConfigurator.configure(WebcamLogConfigurator.java:68)
        at com.github.sarxos.webcam.log.WebcamLogConfigurator.configure(WebcamLogConfigurator.java:90)
        at com.cam.App.main(App.java:47)
```

When I run it with eclipse everything seems to be fine but all I want is a working runnable jar-file.

My pom.xml looks like this:
```
..
<dependencies>
	<dependency>
		<groupId>com.github.sarxos</groupId>
		<artifactId>webcam-capture</artifactId>
		<version>0.3.11</version>
	</dependency>
	<dependency>
		<groupId>com.google.code.gson</groupId>
		<artifactId>gson</artifactId>
		<version>2.6.1</version>
	</dependency>
	<dependency>
		<groupId>org.apache.httpcomponents</groupId>
		<artifactId>httpmime</artifactId>
		<version>4.5.2</version>
	</dependency>
	<dependency>
		<groupId>org.slf4j</groupId>
		<artifactId>slf4j-api</artifactId>
		<version>1.7.18</version>
	</dependency>
	<dependency>
		<groupId>org.slf4j</groupId>
		<artifactId>slf4j-simple</artifactId>
		<version>1.7.18</version>
	</dependency>
	<dependency>
		<groupId>org.slf4j</groupId>
		<artifactId>slf4j-log4j12</artifactId>
		<version>1.7.18</version>
	</dependency>
	<dependency>
		<groupId>ch.qos.logback</groupId>
		<artifactId>logback-classic</artifactId>
		<version>1.1.6</version>
	</dependency>
	<dependency>
		<groupId>ch.qos.logback</groupId>
		<artifactId>logback-core</artifactId>
		<version>1.1.6</version>
	</dependency>
	<dependency>
		<groupId>junit</groupId>
		<artifactId>junit</artifactId>
		<version>4.12</version>
		<scope>test</scope>
	</dependency>
</dependencies>
<build>
	<plugins>
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-compiler-plugin</artifactId>
			<version>3.5.1</version>
			<configuration>
				<source>1.8</source>
				<target>1.8</target>
			</configuration>
		</plugin>
		<plugin>
			<artifactId>maven-assembly-plugin</artifactId>
			<configuration>
				<archive>
					<manifest>
						<mainClass>com.cam.App</mainClass>
					</manifest>
				</archive>
				<descriptorRefs>
					<descriptorRef>jar-with-dependencies</descriptorRef>
				</descriptorRefs>
			</configuration>
		</plugin>
	</plugins>
</build>
..
```

Hope someone can help.

**Comment by MarcJose** [comment]
The example pom.xml was not complete...

**Comment by sarxos** [comment]
Hi @MarcJose,

Thank you for the report.

I never tested how ```WebcamLogConfigurator``` behaves with ```assembly:single``` and it seems being broken. But worry not. This is just utility I wrote to have some more logging options, but in reality, if you are on Logback, you can keep its features by appropriate configuration in your application's executable command line:

```plain
java -Dlogback.configurationFile=/path/to/logback.xml com.cam.App
```

Or in runtime (in the very static main, before LOG is initialized):

```java
public class App {
  static {
    System.setProperty("logback.configurationFile", "/path/to/logback.xml");
  }
}
```

And don't forget to configure your Logback configuration to scan for the changes in loggers settings:

```xml
<configuration scan="true" scanPeriod="5 seconds" >
  ...
</configuration>
```
