### ISSUE TITLE
Webcam open after unregister throws error

### ISSUE THREAD

**Issue by GitPlz** [sarxos/webcam-capture#489]
If an IP camera is registered, then unregistered before close is called, it will not be able to be opened at a later time. Here is example code that will show the problem.

```
        public void test(){
            String url = "<camera url>";
            cameraName = "<camera name>";
            if(!IpCamDeviceRegistry.isRegistered(cameraName)){
                try{
                    IpCamDeviceRegistry.register(cameraName, url, IpCamMode.PUSH);
                }catch(Exception e){
                    logger.error("Error registering camera", e);
                }
            }
            for(Webcam cam : Webcam.getWebcams()){
                if(cam.getName().equals(cameraName)){
                    IpCamDeviceRegistry.unregister(cameraName);
                    if(cam != null && !cam.isOpen()){
                        cam.open(); // throws error
                    }
                    break;
                }
            }
            
        }
```

Exception in thread "Thread-4" com.github.sarxos.webcam.WebcamException: IpCam device not open
	at com.github.sarxos.webcam.ds.ipcam.IpCamDevice.getImage(IpCamDevice.java:299)
	at com.github.sarxos.webcam.ds.ipcam.IpCamDevice.getResolutions(IpCamDevice.java:262)
	at com.github.sarxos.webcam.ds.ipcam.IpCamDevice.getResolution(IpCamDevice.java:285)
	at com.github.sarxos.webcam.ds.cgt.WebcamOpenTask.handle(WebcamOpenTask.java:32)
	at com.github.sarxos.webcam.WebcamTask.process(WebcamTask.java:48)
	at com.github.sarxos.webcam.ds.cgt.WebcamOpenTask.open(WebcamOpenTask.java:20)
	at com.github.sarxos.webcam.Webcam.open(Webcam.java:271)
	at com.github.sarxos.webcam.Webcam.open(Webcam.java:232)

**Comment by somendu** [comment]
you are unregistering the cam first .. and trying to open it ??
