### ISSUE TITLE
java.lang.IllegalStateException: Shutdown in progress at java.io.File.deleteOnExit()

### ISSUE THREAD

**Issue by ecolner** [sarxos/webcam-capture#504]
`[ERROR] com.github.sarxos.webcam.WebcamExceptionHandler - Exception in thread webcam-lock-[Unibrain Fire-i driver / Unibrain Fire-i Board BW]
java.lang.IllegalStateException: Shutdown in progress
        at java.io.DeleteOnExitHook.add(Unknown Source)
        at java.io.File.deleteOnExit(Unknown Source)
        at com.github.sarxos.webcam.WebcamLock.write(WebcamLock.java:125)
        at com.github.sarxos.webcam.WebcamLock.update(WebcamLock.java:273)
        at com.github.sarxos.webcam.WebcamLock.access$200(WebcamLock.java:26)
        at com.github.sarxos.webcam.WebcamLock$LockUpdater.run(WebcamLock.java:58)`

The JDK says:

> Note: this method should <i>not</i> be used for file-locking, as the resulting protocol cannot be made to work reliably. The {@link java.nio.channels.FileLock FileLock} facility should be used instead.

**Comment by ecolner** [comment]
I see that the Webcam class exposes a getLock() and the WebcamLock class exposes disable() so I'll just use that to solve this issue. I'm of the opinion that the lock should be disabled by default, but I guess you can't enable the lock after disabling it so I understand the logic here.
