### ISSUE TITLE
Can't seem to get it to work

### ISSUE THREAD

**Issue by djtobia** [sarxos/webcam-capture#530]
I have a very simple eclipse program written: 

    `import java.awt.image.BufferedImage;
     import java.io.File;
     import java.io.IOException;
     import javax.imageio.ImageIO;
     import com.github.sarxos.webcam.Webcam;

     public class Mirror {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Webcam webcam = Webcam.getDefault();
		if (webcam != null) {
			System.out.println("Webcam: " + webcam.getName());
		} else {
			System.out.println("No webcam detected");
		}
		
		webcam.open();
		BufferedImage image = webcam.getImage();

		// save image to PNG file
		try {
			ImageIO.write(image, "PNG", new File("test.png"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		webcam.close();
		
	}
	

     }
`

and I get this when I try to run it:

Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.github.sarxos.webcam.Webcam.<clinit>(Webcam.java:97)
	at Mirror.main(Mirror.java:13)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more

I have the .jar file added to my build path, what am I doing wrong?

**Comment by sarxos** [comment]
This is very common problem caused by the fact that you haven't add all required JARs into the classpath. Solution is described in ticket https://github.com/sarxos/webcam-capture/issues/158

Take care!
