### ISSUE TITLE
When running Webcam webcam = Webcam.getDefault(); in main()

### ISSUE THREAD

**Issue by FuXual** [sarxos/webcam-capture#547]
When running the code at first i got this:

Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.github.sarxos.webcam.Webcam.<clinit>(Webcam.java:97)
	at camandmic2.CamAndMic2.main(CamAndMic2.java:9)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more

You can close this one as i was not including all the dependencies. Sorry about this!

**Comment by sarxos** [comment]
Sure :) I'm closing it.
