### ISSUE TITLE
How to take a photo usb camera in my android app ?

### ISSUE THREAD

**Issue by amittech1** [sarxos/webcam-capture#623]
How can take a photo in my android app

**Comment by amittech1** [comment]
02/22 14:10:54: Launching app
$ adb push D:\MyApplication\app\build\outputs\apk\debug\app-debug.apk /data/local/tmp/com.cipl.health_tablet.myapplication
$ adb shell pm install -t -r "/data/local/tmp/com.cipl.health_tablet.myapplication"
	pkg: /data/local/tmp/com.cipl.health_tablet.myapplication
Success


$ adb shell am start -n "com.cipl.health_tablet.myapplication/com.cipl.health_tablet.myapplication.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 27536 on device iball-3g_1026_q18-0123456789ABCDEF
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
V/Provider/Settings: invalidate [system]: current 2 != cached 0
D/ActivityThread: hoder:android.app.IActivityManager$ContentProviderHolder@42236208,provider,holder.Provider:android.content.ContentProviderProxy@42236980
V/Provider/Settings: from db cache, name = anr_debugging_mechanism , value = 1
D/asset: AssetManager-->addDefaultAssets CIP path not exsit!
D/Proxy: setHttpRequestCheckHandler
D/dalvikvm: open_cached_dex_file : /data/app/com.cipl.health_tablet.myapplication-1.apk /data/dalvik-cache/data@app@com.cipl.health_tablet.myapplication-1.apk@classes.dex
I/MultiDex: VM with version 1.6.0 does not have multidex support
I/MultiDex: Installing application
I/MultiDex: MultiDexExtractor.load(/data/app/com.cipl.health_tablet.myapplication-1.apk, false, )
I/MultiDex: Blocking on lock /data/data/com.cipl.health_tablet.myapplication/code_cache/secondary-dexes/MultiDex.lock
I/MultiDex: /data/data/com.cipl.health_tablet.myapplication/code_cache/secondary-dexes/MultiDex.lock locked
D/dalvikvm: create interp thread : stack size=128KB
D/dalvikvm: create new thread
D/dalvikvm: new thread created
D/dalvikvm: update thread list
D/dalvikvm: threadid=11: interp stack at 0x600dc000
D/dalvikvm: threadid=11: created from interp
D/dalvikvm: start new thread
D/dalvikvm: threadid=11: notify debugger
D/dalvikvm: threadid=11 (SharedPreferencesImpl-load): calling run()
D/dalvikvm: threadid=11: exiting
D/dalvikvm: threadid=11: bye!
I/MultiDex: Detected that extraction must be performed.
I/MultiDex: Extraction is needed for file /data/data/com.cipl.health_tablet.myapplication/code_cache/secondary-dexes/com.cipl.health_tablet.myapplication-1.apk.classes2.zip
I/MultiDex: Extracting /data/data/com.cipl.health_tablet.myapplication/code_cache/secondary-dexes/tmp-com.cipl.health_tablet.myapplication-1.apk.classes60394523.zip
I/AndroidRuntime: zoneinfo is Asia/Calcutta
I/AndroidRuntime: persist.sys.timezone is Asia/Calcutta
I/MultiDex: Renaming to /data/data/com.cipl.health_tablet.myapplication/code_cache/secondary-dexes/com.cipl.health_tablet.myapplication-1.apk.classes2.zip
I/MultiDex: Extraction succeeded - length /data/data/com.cipl.health_tablet.myapplication/code_cache/secondary-dexes/com.cipl.health_tablet.myapplication-1.apk.classes2.zip: 1387210 - crc: 1311614884
D/dalvikvm: create interp thread : stack size=128KB
D/dalvikvm: create new thread
D/dalvikvm: new thread created
D/dalvikvm: update thread list
D/dalvikvm: threadid=11: interp stack at 0x600dc000
D/dalvikvm: threadid=11: created from interp
D/dalvikvm: start new thread
D/dalvikvm: threadid=11: notify debugger
D/dalvikvm: threadid=11 (SharedPreferencesImpl-load): calling run()
D/dalvikvm: threadid=11: exiting
D/dalvikvm: threadid=11: bye!
I/MultiDex: load found 1 secondary dex files
D/dalvikvm: open_cached_dex_file : /data/data/com.cipl.health_tablet.myapplication/code_cache/secondary-dexes/com.cipl.health_tablet.myapplication-1.apk.classes2.zip /data/data/com.cipl.health_tablet.myapplication/code_cache/secondary-dexes/com.cipl.health_tablet.myapplication-1.apk.classes2.dex
D/dalvikvm: DexOpt: --- BEGIN 'com.cipl.health_tablet.myapplication-1.apk.classes2.zip' (bootstrap=0) ---
D/dalvikvm: threadid=11: interp stack at 0x600e5000
D/dalvikvm: DexOpt: --- END 'com.cipl.health_tablet.myapplication-1.apk.classes2.zip' (success) ---
D/dalvikvm: DEX prep '/data/data/com.cipl.health_tablet.myapplication/code_cache/secondary-dexes/com.cipl.health_tablet.myapplication-1.apk.classes2.zip': unzip in 77ms, rewrite 1079ms
I/MultiDex: install done
D/ActivityThread: BIND_APPLICATION handled : 0 / AppBindData{appInfo=ApplicationInfo{422336f0 com.cipl.health_tablet.myapplication}}
I/dalvikvm: Could not find method android.view.Window$Callback.onPointerCaptureChanged, referenced from method android.support.v7.view.WindowCallbackWrapper.onPointerCaptureChanged
W/dalvikvm: VFY: unable to resolve interface method 11708: Landroid/view/Window$Callback;.onPointerCaptureChanged (Z)V
D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
I/dalvikvm: Could not find method android.view.Window$Callback.onProvideKeyboardShortcuts, referenced from method android.support.v7.view.WindowCallbackWrapper.onProvideKeyboardShortcuts
W/dalvikvm: VFY: unable to resolve interface method 11710: Landroid/view/Window$Callback;.onProvideKeyboardShortcuts (Ljava/util/List;Landroid/view/Menu;I)V
D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
I/dalvikvm: Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.view.WindowCallbackWrapper.onSearchRequested
W/dalvikvm: VFY: unable to resolve interface method 11712: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
I/dalvikvm: Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.view.WindowCallbackWrapper.onWindowStartingActionMode
W/dalvikvm: VFY: unable to resolve interface method 11716: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
I/dalvikvm: Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.widget.TintTypedArray.getChangingConfigurations
W/dalvikvm: VFY: unable to resolve virtual method 255: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
I/dalvikvm: Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.widget.TintTypedArray.getType
W/dalvikvm: VFY: unable to resolve virtual method 277: Landroid/content/res/TypedArray;.getType (I)I
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0008
I/dalvikvm: Could not find method android.content.Context.createDeviceProtectedStorageContext, referenced from method android.support.v4.content.ContextCompat.createDeviceProtectedStorageContext
W/dalvikvm: VFY: unable to resolve virtual method 161: Landroid/content/Context;.createDeviceProtectedStorageContext ()Landroid/content/Context;
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm: Could not find method android.content.Context.getCodeCacheDir, referenced from method android.support.v4.content.ContextCompat.getCodeCacheDir
W/dalvikvm: VFY: unable to resolve virtual method 165: Landroid/content/Context;.getCodeCacheDir ()Ljava/io/File;
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm: Could not find method android.content.Context.getColor, referenced from method android.support.v4.content.ContextCompat.getColor
W/dalvikvm: VFY: unable to resolve virtual method 166: Landroid/content/Context;.getColor (I)I
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm: Could not find method android.content.Context.getColorStateList, referenced from method android.support.v4.content.ContextCompat.getColorStateList
W/dalvikvm: VFY: unable to resolve virtual method 167: Landroid/content/Context;.getColorStateList (I)Landroid/content/res/ColorStateList;
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm: Could not find method android.content.Context.getDataDir, referenced from method android.support.v4.content.ContextCompat.getDataDir
W/dalvikvm: VFY: unable to resolve virtual method 168: Landroid/content/Context;.getDataDir ()Ljava/io/File;
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm: Could not find method android.content.Context.getDrawable, referenced from method android.support.v4.content.ContextCompat.getDrawable
W/dalvikvm: VFY: unable to resolve virtual method 169: Landroid/content/Context;.getDrawable (I)Landroid/graphics/drawable/Drawable;
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm: Could not find method android.content.Context.getNoBackupFilesDir, referenced from method android.support.v4.content.ContextCompat.getNoBackupFilesDir
W/dalvikvm: VFY: unable to resolve virtual method 176: Landroid/content/Context;.getNoBackupFilesDir ()Ljava/io/File;
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm: Could not find method android.content.Context.isDeviceProtectedStorage, referenced from method android.support.v4.content.ContextCompat.isDeviceProtectedStorage
W/dalvikvm: VFY: unable to resolve virtual method 188: Landroid/content/Context;.isDeviceProtectedStorage ()Z
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm: Could not find method android.content.Context.startForegroundService, referenced from method android.support.v4.content.ContextCompat.startForegroundService
W/dalvikvm: VFY: unable to resolve virtual method 197: Landroid/content/Context;.startForegroundService (Landroid/content/Intent;)Landroid/content/ComponentName;
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm: Could not find method android.app.Activity.finishAfterTransition, referenced from method android.support.v4.app.ActivityCompat.finishAfterTransition
W/dalvikvm: VFY: unable to resolve virtual method 71: Landroid/app/Activity;.finishAfterTransition ()V
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm: Could not find method android.app.Activity.getReferrer, referenced from method android.support.v4.app.ActivityCompat.getReferrer
W/dalvikvm: VFY: unable to resolve virtual method 82: Landroid/app/Activity;.getReferrer ()Landroid/net/Uri;
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm: Could not find method android.app.Activity.postponeEnterTransition, referenced from method android.support.v4.app.ActivityCompat.postponeEnterTransition
W/dalvikvm: VFY: unable to resolve virtual method 91: Landroid/app/Activity;.postponeEnterTransition ()V
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm: Could not find method android.app.Activity.requestPermissions, referenced from method android.support.v4.app.ActivityCompat.requestPermissions
W/dalvikvm: VFY: unable to resolve virtual method 92: Landroid/app/Activity;.requestPermissions ([Ljava/lang/String;I)V
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0010
W/dalvikvm: Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl; (46)
W/dalvikvm: Link of class 'Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl;' failed
W/dalvikvm: Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat$SharedElementCallback23Impl; (493)
W/dalvikvm: Link of class 'Landroid/support/v4/app/ActivityCompat$SharedElementCallback23Impl;' failed
E/dalvikvm: Could not find class 'android.support.v4.app.ActivityCompat$SharedElementCallback23Impl', referenced from method android.support.v4.app.ActivityCompat.setEnterSharedElementCallback
W/dalvikvm: VFY: unable to resolve new-instance 495 (Landroid/support/v4/app/ActivityCompat$SharedElementCallback23Impl;) in Landroid/support/v4/app/ActivityCompat;
D/dalvikvm: VFY: replacing opcode 0x22 at 0x0009
I/dalvikvm: Could not find method android.app.Activity.setEnterSharedElementCallback, referenced from method android.support.v4.app.ActivityCompat.setEnterSharedElementCallback
W/dalvikvm: VFY: unable to resolve virtual method 93: Landroid/app/Activity;.setEnterSharedElementCallback (Landroid/app/SharedElementCallback;)V
D/dalvikvm: VFY: replacing opcode 0x6e at 0x000e
W/dalvikvm: Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl; (46)
W/dalvikvm: Link of class 'Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl;' failed
E/dalvikvm: Could not find class 'android.support.v4.app.ActivityCompat$SharedElementCallback21Impl', referenced from method android.support.v4.app.ActivityCompat.setEnterSharedElementCallback
W/dalvikvm: VFY: unable to resolve new-instance 493 (Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl;) in Landroid/support/v4/app/ActivityCompat;
D/dalvikvm: VFY: replacing opcode 0x22 at 0x001a
I/dalvikvm: Could not find method android.app.Activity.setEnterSharedElementCallback, referenced from method android.support.v4.app.ActivityCompat.setEnterSharedElementCallback
W/dalvikvm: VFY: unable to resolve virtual method 93: Landroid/app/Activity;.setEnterSharedElementCallback (Landroid/app/SharedElementCallback;)V
D/dalvikvm: VFY: replacing opcode 0x6e at 0x001f
W/dalvikvm: Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl; (46)
W/dalvikvm: Link of class 'Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl;' failed
W/dalvikvm: Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat$SharedElementCallback23Impl; (493)
W/dalvikvm: Link of class 'Landroid/support/v4/app/ActivityCompat$SharedElementCallback23Impl;' failed
E/dalvikvm: Could not find class 'android.support.v4.app.ActivityCompat$SharedElementCallback23Impl', referenced from method android.support.v4.app.ActivityCompat.setExitSharedElementCallback
W/dalvikvm: VFY: unable to resolve new-instance 495 (Landroid/support/v4/app/ActivityCompat$SharedElementCallback23Impl;) in Landroid/support/v4/app/ActivityCompat;
D/dalvikvm: VFY: replacing opcode 0x22 at 0x0009
I/dalvikvm: Could not find method android.app.Activity.setExitSharedElementCallback, referenced from method android.support.v4.app.ActivityCompat.setExitSharedElementCallback
W/dalvikvm: VFY: unable to resolve virtual method 94: Landroid/app/Activity;.setExitSharedElementCallback (Landroid/app/SharedElementCallback;)V
D/dalvikvm: VFY: replacing opcode 0x6e at 0x000e
W/dalvikvm: Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl; (46)
W/dalvikvm: Link of class 'Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl;' failed
E/dalvikvm: Could not find class 'android.support.v4.app.ActivityCompat$SharedElementCallback21Impl', referenced from method android.support.v4.app.ActivityCompat.setExitSharedElementCallback
W/dalvikvm: VFY: unable to resolve new-instance 493 (Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl;) in Landroid/support/v4/app/ActivityCompat;
D/dalvikvm: VFY: replacing opcode 0x22 at 0x001a
I/dalvikvm: Could not find method android.app.Activity.setExitSharedElementCallback, referenced from method android.support.v4.app.ActivityCompat.setExitSharedElementCallback
W/dalvikvm: VFY: unable to resolve virtual method 94: Landroid/app/Activity;.setExitSharedElementCallback (Landroid/app/SharedElementCallback;)V
D/dalvikvm: VFY: replacing opcode 0x6e at 0x001f
I/dalvikvm: Could not find method android.app.Activity.shouldShowRequestPermissionRationale, referenced from method android.support.v4.app.ActivityCompat.shouldShowRequestPermissionRationale
W/dalvikvm: VFY: unable to resolve virtual method 96: Landroid/app/Activity;.shouldShowRequestPermissionRationale (Ljava/lang/String;)Z
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm: Could not find method android.app.Activity.startPostponedEnterTransition, referenced from method android.support.v4.app.ActivityCompat.startPostponedEnterTransition
W/dalvikvm: VFY: unable to resolve virtual method 103: Landroid/app/Activity;.startPostponedEnterTransition ()V
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
W/dalvikvm: Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl; (46)
W/dalvikvm: Link of class 'Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl;' failed
W/dalvikvm: Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat$SharedElementCallback23Impl; (493)
W/dalvikvm: Link of class 'Landroid/support/v4/app/ActivityCompat$SharedElementCallback23Impl;' failed
D/dalvikvm: DexOpt: unable to opt direct call 0x0921 at 0x0b in Landroid/support/v4/app/ActivityCompat;.setEnterSharedElementCallback
W/dalvikvm: Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl; (46)
W/dalvikvm: Link of class 'Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl;' failed
D/dalvikvm: DexOpt: unable to opt direct call 0x0918 at 0x1c in Landroid/support/v4/app/ActivityCompat;.setEnterSharedElementCallback
W/dalvikvm: Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl; (46)
W/dalvikvm: Link of class 'Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl;' failed
W/dalvikvm: Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat$SharedElementCallback23Impl; (493)
W/dalvikvm: Link of class 'Landroid/support/v4/app/ActivityCompat$SharedElementCallback23Impl;' failed
D/dalvikvm: DexOpt: unable to opt direct call 0x0921 at 0x0b in Landroid/support/v4/app/ActivityCompat;.setExitSharedElementCallback
W/dalvikvm: Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl; (46)
W/dalvikvm: Link of class 'Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl;' failed
D/dalvikvm: DexOpt: unable to opt direct call 0x0918 at 0x1c in Landroid/support/v4/app/ActivityCompat;.setExitSharedElementCallback
I/dalvikvm: Could not find method android.widget.FrameLayout.startActionModeForChild, referenced from method android.support.v7.widget.ActionBarContainer.startActionModeForChild
W/dalvikvm: VFY: unable to resolve virtual method 12038: Landroid/widget/FrameLayout;.startActionModeForChild (Landroid/view/View;Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
D/dalvikvm: VFY: replacing opcode 0x6f at 0x0002
I/dalvikvm: Could not find method android.content.Context.getColorStateList, referenced from method android.support.v7.content.res.AppCompatResources.getColorStateList
W/dalvikvm: VFY: unable to resolve virtual method 373: Landroid/content/Context;.getColorStateList (I)Landroid/content/res/ColorStateList;
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/graphics/drawable/Icon;)
I/dalvikvm: Could not find method android.widget.ImageButton.setImageIcon, referenced from method android.support.v7.widget.AppCompatImageButton.setImageIcon
W/dalvikvm: VFY: unable to resolve virtual method 12055: Landroid/widget/ImageButton;.setImageIcon (Landroid/graphics/drawable/Icon;)V
D/dalvikvm: VFY: replacing opcode 0x6f at 0x0000
I/dalvikvm: Could not find method android.content.res.Resources.getDrawable, referenced from method android.support.v7.widget.ResourcesWrapper.getDrawable
W/dalvikvm: VFY: unable to resolve virtual method 531: Landroid/content/res/Resources;.getDrawable (ILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
I/dalvikvm: Could not find method android.content.res.Resources.getDrawableForDensity, referenced from method android.support.v7.widget.ResourcesWrapper.getDrawableForDensity
W/dalvikvm: VFY: unable to resolve virtual method 533: Landroid/content/res/Resources;.getDrawableForDensity (IILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
W/dalvikvm: VFY: unable to resolve instanceof 183 (Landroid/graphics/drawable/RippleDrawable;) in Landroid/support/v7/widget/AppCompatImageHelper;
D/dalvikvm: VFY: replacing opcode 0x20 at 0x000c
I/dalvikvm: Could not find method android.widget.TextView.getAutoSizeMaxTextSize, referenced from method android.support.v7.widget.AppCompatTextView.getAutoSizeMaxTextSize
W/dalvikvm: VFY: unable to resolve virtual method 12275: Landroid/widget/TextView;.getAutoSizeMaxTextSize ()I
D/dalvikvm: VFY: replacing opcode 0x6f at 0x0006
I/dalvikvm: Could not find method android.widget.TextView.getAutoSizeMinTextSize, referenced from method android.support.v7.widget.AppCompatTextView.getAutoSizeMinTextSize
W/dalvikvm: VFY: unable to resolve virtual method 12276: Landroid/widget/TextView;.getAutoSizeMinTextSize ()I
D/dalvikvm: VFY: replacing opcode 0x6f at 0x0006
I/dalvikvm: Could not find method android.widget.TextView.getAutoSizeStepGranularity, referenced from method android.support.v7.widget.AppCompatTextView.getAutoSizeStepGranularity
W/dalvikvm: VFY: unable to resolve virtual method 12277: Landroid/widget/TextView;.getAutoSizeStepGranularity ()I
D/dalvikvm: VFY: replacing opcode 0x6f at 0x0006
I/dalvikvm: Could not find method android.widget.TextView.getAutoSizeTextAvailableSizes, referenced from method android.support.v7.widget.AppCompatTextView.getAutoSizeTextAvailableSizes
W/dalvikvm: VFY: unable to resolve virtual method 12278: Landroid/widget/TextView;.getAutoSizeTextAvailableSizes ()[I
D/dalvikvm: VFY: replacing opcode 0x6f at 0x0006
I/dalvikvm: Could not find method android.widget.TextView.getAutoSizeTextType, referenced from method android.support.v7.widget.AppCompatTextView.getAutoSizeTextType
W/dalvikvm: VFY: unable to resolve virtual method 12279: Landroid/widget/TextView;.getAutoSizeTextType ()I
D/dalvikvm: VFY: replacing opcode 0x6f at 0x0008
I/dalvikvm: Could not find method android.widget.TextView.setAutoSizeTextTypeUniformWithConfiguration, referenced from method android.support.v7.widget.AppCompatTextView.setAutoSizeTextTypeUniformWithConfiguration
W/dalvikvm: VFY: unable to resolve virtual method 12312: Landroid/widget/TextView;.setAutoSizeTextTypeUniformWithConfiguration (IIII)V
D/dalvikvm: VFY: replacing opcode 0x6f at 0x0006
I/dalvikvm: Could not find method android.widget.TextView.setAutoSizeTextTypeUniformWithPresetSizes, referenced from method android.support.v7.widget.AppCompatTextView.setAutoSizeTextTypeUniformWithPresetSizes
W/dalvikvm: VFY: unable to resolve virtual method 12313: Landroid/widget/TextView;.setAutoSizeTextTypeUniformWithPresetSizes ([II)V
D/dalvikvm: VFY: replacing opcode 0x6f at 0x0006
I/dalvikvm: Could not find method android.widget.TextView.setAutoSizeTextTypeWithDefaults, referenced from method android.support.v7.widget.AppCompatTextView.setAutoSizeTextTypeWithDefaults
W/dalvikvm: VFY: unable to resolve virtual method 12314: Landroid/widget/TextView;.setAutoSizeTextTypeWithDefaults (I)V
D/dalvikvm: VFY: replacing opcode 0x6f at 0x0006
I/dalvikvm: Could not find method android.widget.TextView.getAutoSizeStepGranularity, referenced from method android.support.v7.widget.AppCompatTextHelper.loadFromAttributes
W/dalvikvm: VFY: unable to resolve virtual method 12277: Landroid/widget/TextView;.getAutoSizeStepGranularity ()I
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0197
I/dalvikvm: Could not find method android.text.StaticLayout$Builder.obtain, referenced from method android.support.v7.widget.AppCompatTextViewAutoSizeHelper.createStaticLayoutForMeasuring
W/dalvikvm: VFY: unable to resolve static method 11222: Landroid/text/StaticLayout$Builder;.obtain (Ljava/lang/CharSequence;IILandroid/text/TextPaint;I)Landroid/text/StaticLayout$Builder;
D/dalvikvm: VFY: replacing opcode 0x71 at 0x0014
D/ActivityThread: ACT-AM_ON_RESUME_CALLED ActivityRecord{42235108 token=android.os.BinderProxy@42234688 {com.cipl.health_tablet.myapplication/com.cipl.health_tablet.myapplication.MainActivity}}
V/PhoneWindow: DecorView setVisiblity: visibility = 4 ,Parent =null, this =com.android.internal.policy.impl.PhoneWindow$DecorView{422d5d80 I.E..... R.....ID 0,0-0,0}
V/PhoneWindow: DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{423083b0 com.cipl.health_tablet.myapplication/com.cipl.health_tablet.myapplication.MainActivity,ident = 0}, this =com.android.internal.policy.impl.PhoneWindow$DecorView{422d5d80 V.E..... R.....ID 0,0-0,0}
D/ActivityThread: ACT-LAUNCH_ACTIVITY handled : 0 / ActivityRecord{42235108 token=android.os.BinderProxy@42234688 {com.cipl.health_tablet.myapplication/com.cipl.health_tablet.myapplication.MainActivity}}
D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@422aa220 className=com.cipl.health_tablet.myapplication.WebcamManager packageName=com.cipl.health_tablet.myapplication intent=null}
I/WebcamManager: Service starting
W/dalvikvm: Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/cipl/health_tablet/myapplication/NativeWebcam;
D/AndroidRuntime: Shutting down VM
W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41f4ec98)
W/dalvikvm: threadid=1: uncaught exception occurred
W/System.err: java.lang.UnsatisfiedLinkError: Couldn't load webcam from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.cipl.health_tablet.myapplication-1.apk", zip file "/data/data/com.cipl.health_tablet.myapplication/code_cache/secondary-dexes/com.cipl.health_tablet.myapplication-1.apk.classes2.zip"],nativeLibraryDirectories=[/data/app-lib/com.cipl.health_tablet.myapplication-1, /vendor/lib, /system/lib]]]: findLibrary returned null
W/System.err:     at java.lang.Runtime.loadLibrary(Runtime.java:365)
W/System.err:     at java.lang.System.loadLibrary(System.java:526)
W/System.err:     at com.cipl.health_tablet.myapplication.NativeWebcam.<clinit>(NativeWebcam.java:26)
W/System.err:     at com.cipl.health_tablet.myapplication.WebcamManager.onCreate(WebcamManager.java:28)
W/System.err:     at android.app.ActivityThread.handleCreateService(ActivityThread.java:2731)
W/System.err:     at android.app.ActivityThread.access$1800(ActivityThread.java:151)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:110)
W/System.err:     at android.os.Looper.loop(Looper.java:193)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5292)
W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
W/System.err:     at dalvik.system.NativeStart.main(Native Method)
W/dalvikvm: threadid=1: calling UncaughtExceptionHandler
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.cipl.health_tablet.myapplication, PID: 27536
                  java.lang.UnsatisfiedLinkError: Couldn't load webcam from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.cipl.health_tablet.myapplication-1.apk", zip file "/data/data/com.cipl.health_tablet.myapplication/code_cache/secondary-dexes/com.cipl.health_tablet.myapplication-1.apk.classes2.zip"],nativeLibraryDirectories=[/data/app-lib/com.cipl.health_tablet.myapplication-1, /vendor/lib, /system/lib]]]: findLibrary returned null
                      at java.lang.Runtime.loadLibrary(Runtime.java:365)
                      at java.lang.System.loadLibrary(System.java:526)
                      at com.cipl.health_tablet.myapplication.NativeWebcam.<clinit>(NativeWebcam.java:26)
                      at com.cipl.health_tablet.myapplication.WebcamManager.onCreate(WebcamManager.java:28)
                      at android.app.ActivityThread.handleCreateService(ActivityThread.java:2731)
                      at android.app.ActivityThread.access$1800(ActivityThread.java:151)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
                      at android.os.Handler.dispatchMessage(Handler.java:110)
                      at android.os.Looper.loop(Looper.java:193)
                      at android.app.ActivityThread.main(ActivityThread.java:5292)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
                      at dalvik.system.NativeStart.main(Native Method)
I/Process: Sending signal. PID: 27536 SIG: 9
Application terminated.

**Comment by sarxos** [comment]
Hi @amittech1. This library does not support Android. Sorry.
