### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError, due to dependency conflict issues caused by com.nativelibs4java:bridj:jar

### ISSUE THREAD

**Issue by LeoAugust19** [sarxos/webcam-capture#653]
Hi, we found multiple versions of **com.nativelibs4java:bridj:jar** exist in **com.github.sarxos:webcam-capture-driver-openimaj:jar:0.3.12**, as shown in the following dependency tree, based on "Maven's nearest wins strategy" only the older version 0.6.2 will be loaded and the newer version 0.7.0 will be shadowed.

However, method **<org.bridj.Pointer: org.bridj.Pointer getPointer(org.bridj.NativeObject)>**  only defined in  com.nativelibs4java:bridj:jar:0.7.0, an exception will be thrown when your project referencing it.

### Dependency tree
com.github.sarxos:webcam-capture-driver-openimaj:jar:0.3.12
+- com.github.sarxos:webcam-capture:jar:0.3.12:compile
|  +- (com.nativelibs4java:bridj:jar:0.7.0:compile - omitted for conflict with 0.6.2)
|  \- org.slf4j:slf4j-api:jar:1.7.2:compile
+- com.nativelibs4java:bridj:jar:0.6.2:compile
|  \- com.google.android.tools:dx:jar:1.7:compile
\- org.openimaj:core-video-capture:jar:1.3:compile
   +- org.openimaj:core-video:jar:1.3:compile
   \- (com.nativelibs4java:bridj:jar:0.7-20140918:compile - omitted for conflict with 0.6.2)

### Stack trace
Exception in thread "main" java.lang.NoSuchMethodError: org.bridj.Pointer.getPointer(Lorg/bridj/NativeObject;)Lorg/bridj/Pointer;
	at org.openimaj.video.capture.VideoCapture.startSession(VideoCapture.java:231)
	at org.openimaj.video.capture.VideoCapture.<init>(VideoCapture.java:184)
	at com.github.sarxos.webcam.ds.openimaj.OpenImajDevice.open(OpenImajDevice.java:92)

### Solution
Use com.nativelibs4java:bridj:jar:0.7.0 in your pom.xml.

May pull a request to fix it?
Thanks!

Regards,
Leo

**Comment by LeoAugust19** [comment]
@jonburgin Hi, the above information is obtained by static analysis. Do you need further information to confirm it's a bug? Maybe I can provide you more.

**Comment by LeoAugust19** [comment]
### Stack trace

Exception in thread "main" java.lang.NoSuchMethodError: org.bridj.Pointer.getPointer(Lorg/bridj/NativeObject;)Lorg/bridj/Pointer;
	at org.openimaj.video.capture.VideoCapture.startSession(VideoCapture.java:231)
	at org.openimaj.video.capture.VideoCapture.<init>(VideoCapture.java:184)
	at com.github.sarxos.webcam.ds.openimaj.OpenImajDevice.open(OpenImajDevice.java:92)

**Comment by LeoAugust19** [comment]
@sarxos Hi, could you please help review this PR?

Thanks a lot.

Regards,
Leo
