### ISSUE TITLE
hi @MuhammadAmmad ,

### ISSUE THREAD

**Issue by sachinrke** [sarxos/webcam-capture#662]
Thanks for the code. I have also tried your code and able to record video from multiple cameras. but this code not recording audio with video.so how can we record audio with video together from multiple cameras. please help me.
 i will be very grateful to you.

Thank You 
sachin pal

_Originally posted by @sachinrke in https://github.com/sarxos/webcam-capture/issue_comments#issuecomment-427737822_

**Comment by sarxos** [comment]
Hi @sachinrke,

I never intended to add audio support to webcam capture because the main goal of this library is to access video feed from camera.

But if you are interested in audio support then please take a look at this code: https://github.com/ryancheu/webcam-capture/commit/25d63d6c822a5aa3483e22c0ebb16f889276b666, a modified live feed example which includes audio streaming.

**Comment by sachinrke** [comment]
hi@sarxos,
Thanks for reply, however  i would like to intimate you that i have recorded audio with video but the problem is that
1.  audio comes in half video and half part is without audio 
2. when i am recording from multiple cameras it give me null pointer exception in method getAudioSamples(int fps) line audioLine.start();

i have send the code.
please help me where i am doing wrong. my knowledge in limited.
your help will be much appreciated.
Thank you.

Exception in thread "Thread-11" java.lang.NullPointerException
	at cam.WebcamViewerExample.getAudioSamples(WebcamViewerExample.java:275)
	at cam.WebcamViewerExample.saveClip(WebcamViewerExample.java:152)
	at cam.WebcamViewerExample.access$000(WebcamViewerExample.java:36)
	at cam.WebcamViewerExample$SaveClip.run(WebcamViewerExample.java:207) 

WebcamApp.java
if("Start Recording".equals(e.getActionCommand())){
            if(dw.availableUSBCameralist.get(0).isOpen() && !dw.availableUSBCameralist.get(1).isOpen()){
                new WebcamViewerExample.Capture(dw.availableUSBCameralist.get(0)).start();
            }
            if(!dw.availableUSBCameralist.get(0).isOpen() && dw.availableUSBCameralist.get(1).isOpen()){
                new WebcamViewerExample.Capture(dw.availableUSBCameralist.get(1)).start();
            }
            if(dw.availableUSBCameralist.get(0).isOpen() && dw.availableUSBCameralist.get(1).isOpen()){
                new WebcamViewerExample.Capture(dw.availableUSBCameralist.get(0)).start();
                 new WebcamViewerExample.Capture(dw.availableUSBCameralist.get(1)).start();
}
}

WebcamViewerExample.java
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamResolution;
import com.github.sarxos.webcam.ds.ipcam.IpCamDevice;
import com.xuggle.mediatool.IMediaWriter;
import com.xuggle.mediatool.ToolFactory;
import com.xuggle.xuggler.IAudioSamples;
import com.xuggle.xuggler.ICodec;
import com.xuggle.xuggler.IPixelFormat;
import com.xuggle.xuggler.IVideoPicture;
import com.xuggle.xuggler.video.ConverterFactory;
import com.xuggle.xuggler.video.IConverter;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.TargetDataLine;

public class WebcamViewerExample {
    public static int record_time = 10; // recording time is 10s
    public static int fps = 30;
    public static final int CHANNEL_COUNT = 2;
    public static final int SAMPLE_RATE = 44100;
    public static final IAudioSamples.Format soundFormat = IAudioSamples.Format.FMT_S16;
    public static final int BYTE_DEPTH = soundFormat.swigValue() + 1;
    public static final int BIT_DEPTH = 8 * BYTE_DEPTH;
    public static int audioTime = 0;
    public static TargetDataLine audioLine = null;
    public static AudioFormat audioFormat = null;
    //private static final long startTime = System.nanoTime();
    static Capture cap;
    public static WebcamViewerExample ref;
    /*public static void main(String[] args) throws MalformedURLException {
        Webcam.setDriver(new IpCamDriver(new IpCamStorage("e:/sachin/ipxml.xml")));
        //Capture cap = new Capture(Webcam.getWebcams()) ;
        for (Webcam webcam : Webcam.getWebcams()) {
            cap = new Capture(webcam);
            new Capture(webcam).start();
        }
        //Timer time = new Timer(); // Instantiate Timer Object
	//ScheduledTask st = new ScheduledTask(); // Instantiate SheduledTask class
	//time.schedule(cap, 0, 1000); // Create Repetitively task for every 1 secs
    }*/
    
    public WebcamViewerExample(){
        ref=this;
    }
    public void recordVideo(Webcam webcam,String parentDir,int duration)  {
        String camName = webcam.getName();
        Date date=new Date(System.currentTimeMillis());
        Calendar calendar=Calendar.getInstance();
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");  
        String strDate= formatter.format(date);  
        String pathToSave=parentDir+"/"+camName+"/"+strDate;
        String fileName=calendar.get(Calendar.HOUR_OF_DAY)+"-"+calendar.get(Calendar.MINUTE)+"-"+calendar.get(Calendar.SECOND);

        if(!createFolder(pathToSave)){
            System.out.println("Cant access path.");
            return;
        }
        
        File file = new File(pathToSave+"/"+fileName+".mp4");
        long start = System.currentTimeMillis();
        Dimension size = WebcamResolution.VGA.getSize();
        ArrayList<VideoPic> bufferedImgs=new ArrayList<>();
        for (int i = 0; i < duration*10; i++) {
            System.out.println(camName + " " + "Capture frame " + i);
            bufferedImgs.add(new VideoPic(webcam.getImage(), System.currentTimeMillis()));
            //bufferedImgs.add(new VideoPic(webcam.getImage(), start));
            // 10 FPS
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                System.out.println(e.getMessage());
            }
        }
        
            new SaveClip(size, file, start, bufferedImgs).start();
        
    }
    
    public void recordVideo(IpCamDevice ipwebcam,String parentDir,int duration)  {
        String camName = ipwebcam.getName();
        Date date=new Date(System.currentTimeMillis());
        Calendar calendar=Calendar.getInstance();
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");  
        String strDate= formatter.format(date);  
        String pathToSave=parentDir+"/"+camName+"/"+strDate;
        String fileName=calendar.get(Calendar.HOUR_OF_DAY)+"-"+calendar.get(Calendar.MINUTE)+"-"+calendar.get(Calendar.SECOND);

        if(!createFolder(pathToSave)){
            System.out.println("Cant access path.");
            return;
        }
        
        File file = new File(pathToSave+"/"+fileName+".mp4");
        long start = System.currentTimeMillis();
        Dimension size = WebcamResolution.VGA.getSize();
        ArrayList<VideoPic> bufferedImgs=new ArrayList<>();
        for (int i = 0; i < duration*10; i++) {
            System.out.println(camName + " " + "Capture frame " + i);
            bufferedImgs.add(new VideoPic(ipwebcam.getImage(), System.currentTimeMillis()));
            //bufferedImgs.add(new VideoPic(webcam.getImage(), start));
            // 10 FPS
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                System.out.println(e.getMessage());
            }
        }
        
            new SaveClip(size, file, start, bufferedImgs).start();
        
    }
    
    private void saveClip(Dimension size,File file, long start,ArrayList<VideoPic> arr) {
        IMediaWriter writer = ToolFactory.makeWriter(file.getAbsolutePath());
        writer.addVideoStream(0, 0, ICodec.ID.CODEC_ID_H264, size.width,size.height);
        writer.addAudioStream(1, 0, ICodec.ID.CODEC_ID_AAC, 2, 44100);
        try{
            openAudioRecorder();
        }catch(LineUnavailableException le){
            System.out.println(le.getMessage());
        }
        for (int i = 0; i < arr.size(); i++){
                VideoPic videoPic=arr.get(i);
                if(videoPic.getBufferedImage()!=null){
                    BufferedImage image = ConverterFactory.convertToType(videoPic.getBufferedImage(), BufferedImage.TYPE_3BYTE_BGR);
                    IConverter converter = ConverterFactory.createConverter(image,IPixelFormat.Type.YUV420P);
                    IVideoPicture frame = converter.toPicture(image,i * 100000);
                    System.out.println("time-start: "+(videoPic.getTime() - start)+"");
                    frame.setKeyFrame(i == 0);
                    frame.setQuality(0);
                    writer.encodeVideo(0, frame);
                    writer.encodeAudio(1, getAudioSamples(fps));
                }
        }
        closeAudioRecorder();
        writer.close();
        
        System.out.println("Video recorded in file: " + file.getAbsolutePath());
    }
    
    public static final class Capture extends Thread {
        Webcam webcam;
        IpCamDevice ipwebcam;
        public Capture(Webcam webcam) {
            this.webcam = webcam;
        }
        public Capture(IpCamDevice ipwebcam) {
            this.ipwebcam = ipwebcam;
        }
        
        
        @Override
        public void run()  {
            while(true){
                synchronized(this){
                    if(webcam!=null){
                        new WebcamViewerExample().recordVideo(webcam,"e:/",10);
                    }
                    if(ipwebcam!=null){
                        new WebcamViewerExample().recordVideo(ipwebcam,"e:/",100);
                    }
                }try{
                Thread.sleep(16000);
                }catch(Exception e){}
            }
            
        }
    }
    
    private static final class SaveClip extends Thread {
        Dimension size;
        File file;
        long start;
        ArrayList<VideoPic> bufferedImgs;
        int fps;
        public SaveClip(Dimension size, File file, long start,ArrayList<VideoPic> bufferedImgs) {
            super();
            this.size = size;
            this.file = file;
            this.start = start;
            this.bufferedImgs = bufferedImgs;
            //this.fps=fps;
        }
        @Override
        public void run() {
                synchronized(this){
                    new WebcamViewerExample().saveClip(size, file, start, bufferedImgs);
                }
                try{
                Thread.sleep(5000);
                }catch(Exception e){}
        }
    }

    private static boolean createFolder(String theFilePath) {
        boolean result = false;
        File directory = new File(theFilePath);
        if (directory.exists()) {
            System.out.println("Folder already exists");
            result=true;
        } else {
            result = directory.mkdirs();
        }
        return result;
    }
    
    public class VideoPic{
        BufferedImage bufferedImage;
        long time;
        public VideoPic(BufferedImage bufferedImage, long time) {
            super();
            this.bufferedImage = bufferedImage;
            this.time = time;
        }
        public BufferedImage getBufferedImage() {
            return bufferedImage;
        }
        public void setBufferedImage(BufferedImage bufferedImage) {
            this.bufferedImage = bufferedImage;
        }
        public long getTime() {
            return time;
        }
        public void setTime(long time) {
            this.time = time;
        }
    }
    
    
     public static AudioFormat getAudioFormat() {
        if (audioFormat == null) {
            audioFormat = new AudioFormat(SAMPLE_RATE, BIT_DEPTH, CHANNEL_COUNT, true, false);
        }
        return audioFormat;
    }

    public static void openAudioRecorder() throws LineUnavailableException {
        DataLine.Info info = new DataLine.Info(TargetDataLine.class, getAudioFormat());
        System.out.println(info);
        audioLine = (TargetDataLine) AudioSystem.getLine(info);
        audioLine.open(getAudioFormat());
        audioTime = 0;
    }

    public static IAudioSamples getAudioSamples(int fps) {
        if (fps <= 0)
            fps = 1;

        IAudioSamples samples = IAudioSamples.make(SAMPLE_RATE / fps, CHANNEL_COUNT, soundFormat);
       
        audioLine.start();
        
        byte[] data = new byte[(SAMPLE_RATE * BYTE_DEPTH * CHANNEL_COUNT) / fps];
        
        int sz = audioLine.read(data, 0, data.length);
        samples.put(data, 0, 0, sz);
        audioTime += (sz);
        samples.setComplete(true, sz / (BYTE_DEPTH * CHANNEL_COUNT), SAMPLE_RATE, CHANNEL_COUNT, soundFormat,
                audioTime / (BYTE_DEPTH * CHANNEL_COUNT));
        
        return samples;
    }

    public static void closeAudioRecorder() {
        if (audioLine != null) {
            audioLine.close();
            audioLine = null;
        }
    }
}
