### ISSUE TITLE
Exception occured NoClassDefFoundError: org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by connerelf** [sarxos/webcam-capture#664]
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.github.sarxos.webcam.Webcam.<clinit>(Webcam.java:97)
	at webcam.Main.<init>(Main.java:13)
	at webcam.Main.main(Main.java:22)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 3 more

i tried the example code but i got this error.

**Comment by mj0stjo** [comment]
I fixed this Error by downloading [slf4j-1.7.25.zip](https://www.slf4j.org/download.html). It contains slf4j-api-1.7.25.jar and slf4j-simple-1.7.25.jar . I added them to my project and then it worked.
