### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: com/github/sarxos/webcam/Webcam

### ISSUE THREAD

**Issue by danper2213** [sarxos/webcam-capture#688]
I just run this code and when run it for command line the error is the next:

public static void main(String[] args) {
        Webcam webcam = Webcam.getDefault();
        if (webcam != null) {
            System.out.println("Webcam: " + webcam.getName());
        } else {
            System.out.println("No webcam detected");
        }
    }

---------------------------------------------------------------------------------------------------------------------------
Exception in thread "main" java.lang.NoClassDefFoundError: com/github/sarxos/webcam/Webcam
	at com.superaccess.mavenproject1.App.main(App.java:15)
Caused by: java.lang.ClassNotFoundException: com.github.sarxos.webcam.Webcam
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

**Comment by danper2213** [comment]
Thank you for your help ! 

Now, i'm trying run the same project in a raspberrypi but i have the next error.

`sudo java -Dwebcam.debug=true -Dbridj.debug=true -Dbridj.veryVerbose=true -Dbridj.verbose=true -Djava.library.path=/home/pi/Alistamiento_ARM/Neurotec_Biometric_10_0_SDK/Lib/Linux_armhf -jar Enroll-Console-1.0-SNAPSHOT-jar-with-dependencies.jar`


SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
ene 28, 2019 7:46:26 AM org.bridj.BridJ log
INFORMACIÓN: Embedded paths for library bridj : [org/bridj/v0_6_2/lib/linux_arm32_arm/libbridj.so, org/bridj/v0_6_2/lib/linux_arm32_arm/bridj.so, org/bridj/lib/linux_arm32_arm/libbridj.so, org/bridj/lib/linux_arm32_arm/bridj.so, lib/linux_arm32_arm/libbridj.so, lib/linux_arm32_arm/bridj.so]
ene 28, 2019 7:46:26 AM org.bridj.BridJ log
INFORMACIÓN: Loading library /tmp/BridJExtractedLibraries3645557900724238589/bridj.so
Java HotSpot(TM) Client VM warning: You have loaded library /tmp/BridJExtractedLibraries3645557900724238589/bridj.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
java.lang.RuntimeException: Failed to initialize BridJ
	at org.bridj.Platform.initLibrary(Platform.java:370)
	at org.bridj.Platform.<clinit>(Platform.java:175)
	at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.<clinit>(OpenIMAJGrabber.java:59)
	at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.handle(WebcamDefaultDriver.java:55)
	at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/BridJExtractedLibraries3645557900724238589/bridj.so: /tmp/BridJExtractedLibraries3645557900724238589/bridj.so: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bridj.Platform.initLibrary(Platform.java:347)
	... 7 more
Exception in thread "main" com.github.sarxos.webcam.WebcamException: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
	at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:124)
	at com.github.sarxos.webcam.Webcam.getWebcams(Webcam.java:893)
	at com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:956)
	at com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:933)
	at com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:911)
	at com.superaccess.enroll.console.CapturarFoto.<init>(CapturarFoto.java:47)
	at com.superaccess.enroll.console.App.<init>(App.java:67)
	at com.superaccess.enroll.console.App.main(App.java:341)
Caused by: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:116)
	... 7 more
Caused by: com.github.sarxos.webcam.WebcamException: Cannot execute task
	at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.process(WebcamProcessor.java:72)
	at com.github.sarxos.webcam.WebcamProcessor.process(WebcamProcessor.java:140)
	at com.github.sarxos.webcam.WebcamTask.process(WebcamTask.java:46)
	at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.newGrabber(WebcamDefaultDriver.java:45)
	at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver.getDevices(WebcamDefaultDriver.java:117)
	at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:36)
	at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsatisfiedLinkError: org.bridj.Platform.sizeOf_ptrdiff_t()I
	at org.bridj.Platform.sizeOf_ptrdiff_t(Native Method)
	at org.bridj.Platform.<clinit>(Platform.java:179)
	at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.<clinit>(OpenIMAJGrabber.java:59)
	at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.handle(WebcamDefaultDriver.java:55)
	at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:81)
	... 3 more
