### ISSUE TITLE
Program shut down when closing a webcam

### ISSUE THREAD

**Issue by nestormariomace** [sarxos/webcam-capture#699]
Hello.
I'm programming an application that requires to read 3 images from 3 webcams, store them in a disk as a "jpg", and store an additional file in the disk once each aprox. 15 seconds..
I'm working in a PC with Windows 10 and developing the program with Netbeans 7.3.1; jdk1.7.
The application is a do-forever that opens the webcam using
webcam1 = webcams.get(i);
if (!webcam1.isOpen()){
    webcam1.setCustomViewSizes(size);
    webcam1.setViewSize(size[0]);
    webcam1.open(false);
}
Then reads and store
 try{
     imgFoto[i] = webcam1.getImage();
     ImageIO.write(imgFoto[i], "JPG", new File("U:/PruebaMaster/SLV" + nslv + "/Foto" + i + ".jpg"));
     out = new FileOutputStream("U:/PruebaMaster/SLV" + nslv + "/bandera" + i);
     try{
         out.write((int)0X42);
     }
     catch(Exception e){}
     finally{
         out.close();
     }
Then closes the webcam
     webcam1.close();

When the program is running, and in a non deterministic way, the program shuts down with
a message in the output netbeans window
     Java result -1073741819
It seems the program shuts down when closing one of the webcams.
In just one case, the program finished with a message
Exception in thread "Thread-4" com.github.sarxos.webcam.WebcamLockException: Webcam IPEVO Ziggi-HD Plus 0 has already been locked
	at com.github.sarxos.webcam.WebcamLock.lock(WebcamLock.java:286)
	at com.github.sarxos.webcam.Webcam.open(Webcam.java:265)
	at latuslv.VentanaPrincipal$LecturaAlmacenamiento.run(VentanaPrincipal.java:703)
	at java.lang.Thread.run(Thread.java:724)
Line 703 is an webcam1.open(false); after having been closed.
Can you help me?

**Comment by nestormariomace** [comment]
I'm getting the same problem with the much simpler program below:

                    while (true){                        
                        for (int k = 0; k < webcams.size(); k++){
                            try{
                                webcam1 = webcams.get(k);
                                if ( ! webcam1.isOpen()){
                                    webcam1.setCustomViewSizes(size);
                                    webcam1.setViewSize(size[0]);
                                    webcam1.open(true);                                    
                                }
                                webcam1.close();
                             }
                            catch(Exception ee){
                                System.out.println("xxxx.");
                            }
                        }                        
                    }
It fails after running a few minutes.
