### ISSUE TITLE
MacOS - Webcam Open Problem 

### ISSUE THREAD

**Issue by cengizerdoganrk** [sarxos/webcam-capture#755]
Hi @sarxos;
On MacOS, we are facing the following exception quite frequently.
Any idea how to resolve this?
Thanks.

2019-12-03 10:16:26,993 pool-14-thread-2                 ERROR WebcamCaptureTask                 Cannot capture image
com.github.sarxos.webcam.WebcamException: Cannot execute task
	at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.process(WebcamProcessor.java:72)
	at com.github.sarxos.webcam.WebcamProcessor.process(WebcamProcessor.java:140)
	at com.github.sarxos.webcam.WebcamTask.process(WebcamTask.java:46)
	at com.github.sarxos.webcam.ds.cgt.WebcamOpenTask.open(WebcamOpenTask.java:20)
	at com.github.sarxos.webcam.Webcam.open(Webcam.java:295)
	at com.github.sarxos.webcam.Webcam.open(Webcam.java:250)
	at com.github.sarxos.webcam.Webcam.open(Webcam.java:236)
	at com.virtualoffice.client.capture.webcam.WebcamCaptureTask.openWebcam(WebcamCaptureTask.java:139)
	at com.virtualoffice.client.capture.webcam.WebcamCaptureTask.captureImage(WebcamCaptureTask.java:118)
	at com.virtualoffice.client.capture.webcam.WebcamCaptureTask.capture(WebcamCaptureTask.java:48)
	at com.virtualoffice.client.capture.webcam.WebcamCaptureTask.execute(WebcamCaptureTask.java:38)
	at com.virtualoffice.client.capture.webcam.WebcamCapture.capture(WebcamCapture.java:60)
	at com.virtualoffice.client.capture.webcam.WebcamCapture.capture(WebcamCapture.java:56)
	at com.virtualoffice.client.datacapture.jobs.WebcamshotJob.saveEvent(WebcamshotJob.java:64)
	at com.virtualoffice.client.datacapture.jobs.AbstractImageCaptureJob.run(AbstractImageCaptureJob.java:56)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.github.sarxos.webcam.WebcamException: org.bytedeco.javacv.FrameGrabber$Exception: read() Error: Could not read frame in start().
	at com.github.sarxos.webcam.ds.javacv.JavaCvDevice.open(JavaCvDevice.java:200)
	at com.github.sarxos.webcam.ds.cgt.WebcamOpenTask.handle(WebcamOpenTask.java:38)
	at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:81)
	... 3 more
Caused by: org.bytedeco.javacv.FrameGrabber$Exception: read() Error: Could not read frame in start().
	at org.bytedeco.javacv.OpenCVFrameGrabber.start(OpenCVFrameGrabber.java:240)
	at com.github.sarxos.webcam.ds.javacv.JavaCvDevice.open(JavaCvDevice.java:194)
	... 5 more

**Comment by kkieffer** [comment]
Duplicate of #645 I think.
