### ISSUE TITLE
Not Working On Raspberry Pi (V4l4j, Raspberry Pi 4 4gb)

### ISSUE THREAD

**Issue by Liquid-Dev0001** [sarxos/webcam-capture#787]
I want to run my Camera Program on my Raspberry Pi. Im using [this](https://github.com/sarxos/webcam-capture/wiki/How-To-Configure-Raspberry-Pi) example. I have installed all libraries i guess and the code cant be wrong. 

My Error:

```WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.github.sarxos.v4l4j.NativeUtils (file:/home/pi/Desktop/RaspiCamTest.jar) to field java.lang.ClassLoader.usr_paths
WARNING: Please consider reporting this to the maintainers of com.github.sarxos.v4l4j.NativeUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[ libvideo.c:68 ] Using libvideo version 0.9-UNKNOWN
[ v4l4j_ResolutionInfo.c:57 ] [V4L4J] Error looking up the palette with index 74
au.edu.jcu.v4l4j.exceptions.JNIException: Error looking up image format
	at au.edu.jcu.v4l4j.ResolutionInfo.doGetType(Native Method)
	at au.edu.jcu.v4l4j.ResolutionInfo.<init>(ResolutionInfo.java:145)
	at au.edu.jcu.v4l4j.ImageFormat.<init>(ImageFormat.java:84)
	at au.edu.jcu.v4l4j.ImageFormatList.listFormats(Native Method)
	at au.edu.jcu.v4l4j.ImageFormatList.<init>(ImageFormatList.java:111)
	at au.edu.jcu.v4l4j.DeviceInfo.getInfo(Native Method)
	at au.edu.jcu.v4l4j.DeviceInfo.<init>(DeviceInfo.java:254)
	at au.edu.jcu.v4l4j.VideoDevice.initDeviceInfo(VideoDevice.java:298)
	at au.edu.jcu.v4l4j.VideoDevice.<init>(VideoDevice.java:274)
	at com.github.sarxos.webcam.ds.v4l4j.V4l4jDevice.getVideoDevice(V4l4jDevice.java:105)
	at com.github.sarxos.webcam.ds.v4l4j.V4l4jDevice.<init>(V4l4jDevice.java:89)
	at com.github.sarxos.webcam.ds.v4l4j.V4l4jDriver.getDevices(V4l4jDriver.java:49)
	at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:36)
	at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
There was an error checking the supported resolutions.
Please report this error to thev4l4j mailing list.
See REAME file for information on reporting bugs
[ v4l4j_ResolutionInfo.c:57 ] [V4L4J] Error looking up the palette with index 74
au.edu.jcu.v4l4j.exceptions.JNIException: Error looking up image format
	at au.edu.jcu.v4l4j.ResolutionInfo.doGetType(Native Method)
	at au.edu.jcu.v4l4j.ResolutionInfo.<init>(ResolutionInfo.java:145)
	at au.edu.jcu.v4l4j.ImageFormat.<init>(ImageFormat.java:84)
	at au.edu.jcu.v4l4j.ImageFormatList.listFormats(Native Method)
	at au.edu.jcu.v4l4j.ImageFormatList.<init>(ImageFormatList.java:111)
	at au.edu.jcu.v4l4j.DeviceInfo.getInfo(Native Method)
	at au.edu.jcu.v4l4j.DeviceInfo.<init>(DeviceInfo.java:254)
	at au.edu.jcu.v4l4j.VideoDevice.initDeviceInfo(VideoDevice.java:298)
	at au.edu.jcu.v4l4j.VideoDevice.<init>(VideoDevice.java:274)
	at com.github.sarxos.webcam.ds.v4l4j.V4l4jDevice.getVideoDevice(V4l4jDevice.java:105)
	at com.github.sarxos.webcam.ds.v4l4j.V4l4jDevice.<init>(V4l4jDevice.java:89)
	at com.github.sarxos.webcam.ds.v4l4j.V4l4jDriver.getDevices(V4l4jDriver.java:49)
	at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:36)
	at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
There was an error checking the supported resolutions.
Please report this error to thev4l4j mailing list.
See REAME file for information on reporting bugs
[ v4l4j_ResolutionInfo.c:57 ] [V4L4J] Error looking up the palette with index 74
au.edu.jcu.v4l4j.exceptions.JNIException: Error looking up image format
	at au.edu.jcu.v4l4j.ResolutionInfo.doGetType(Native Method)
	at au.edu.jcu.v4l4j.ResolutionInfo.<init>(ResolutionInfo.java:145)
	at au.edu.jcu.v4l4j.ImageFormat.<init>(ImageFormat.java:84)
	at au.edu.jcu.v4l4j.ImageFormatList.listFormats(Native Method)
	at au.edu.jcu.v4l4j.ImageFormatList.<init>(ImageFormatList.java:111)
	at au.edu.jcu.v4l4j.DeviceInfo.getInfo(Native Method)
	at au.edu.jcu.v4l4j.DeviceInfo.<init>(DeviceInfo.java:254)
	at au.edu.jcu.v4l4j.VideoDevice.initDeviceInfo(VideoDevice.java:298)
	at au.edu.jcu.v4l4j.VideoDevice.<init>(VideoDevice.java:274)
	at com.github.sarxos.webcam.ds.v4l4j.V4l4jDevice.getVideoDevice(V4l4jDevice.java:105)
	at com.github.sarxos.webcam.ds.v4l4j.V4l4jDevice.<init>(V4l4jDevice.java:89)
	at com.github.sarxos.webcam.ds.v4l4j.V4l4jDriver.getDevices(V4l4jDriver.java:49)
	at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:36)
	at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
There was an error checking the supported resolutions.
Please report this error to thev4l4j mailing list.
See REAME file for information on reporting bugs
[ v4l4j_ResolutionInfo.c:57 ] [V4L4J] Error looking up the palette with index 74
au.edu.jcu.v4l4j.exceptions.JNIException: Error looking up image format
	at au.edu.jcu.v4l4j.ResolutionInfo.doGetType(Native Method)
	at au.edu.jcu.v4l4j.ResolutionInfo.<init>(ResolutionInfo.java:145)
	at au.edu.jcu.v4l4j.ImageFormat.<init>(ImageFormat.java:84)
	at au.edu.jcu.v4l4j.ImageFormatList.listFormats(Native Method)
	at au.edu.jcu.v4l4j.ImageFormatList.<init>(ImageFormatList.java:111)
	at au.edu.jcu.v4l4j.DeviceInfo.getInfo(Native Method)
	at au.edu.jcu.v4l4j.DeviceInfo.<init>(DeviceInfo.java:254)
	at au.edu.jcu.v4l4j.VideoDevice.initDeviceInfo(VideoDevice.java:298)
	at au.edu.jcu.v4l4j.VideoDevice.<init>(VideoDevice.java:274)
	at com.github.sarxos.webcam.ds.v4l4j.V4l4jDevice.getVideoDevice(V4l4jDevice.java:105)
	at com.github.sarxos.webcam.ds.v4l4j.V4l4jDevice.<init>(V4l4jDevice.java:89)
	at com.github.sarxos.webcam.ds.v4l4j.V4l4jDriver.getDevices(V4l4jDriver.java:49)
	at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:36)
	at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
There was an error checking the supported resolutions.
Please report this error to thev4l4j mailing list.
See REAME file for information on reporting bugs
[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:484 ] libvideo has skipped an unsupported image format:
[ v4l2-query.c:485 ] YUV 4:2:0 (M420) (0x3032344d)
[ v4l2-query.c:486 ] Please let the author know about this error.
[ v4l2-query.c:487 ] See the ISSUES section in the libvideo README file.
^C[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit
a bug report on the v4l4j mailing list.[ v4l2-query.c:49 ] Error looking up V4L2 format 3032344d. Please submit```

After that i get thousands of "We shouldnt be here..." messages


My libraries:
![My Libraries](https://user-images.githubusercontent.com/54677650/94350078-eb49e300-004a-11eb-80a5-ffd4bf2371b2.png)

**Comment by ZMizgalski** [comment]
Same
