### ISSUE TITLE
JProfiler & webcam app

### ISSUE THREAD

**Issue by vtomanov** [sarxos/webcam-capture#80]
When try to run application using webcam inside JProfiler the following error is displayed and the webcam lid do not work...

```
Apr 11, 2013 8:51:27 PM net.b2net.data.client.motion.SnapGenerator tryAttachCam
INFO: Try to attach Webcam...
Exception in thread "processor-1" java.lang.UnsatisfiedLinkError: com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.__jprofiler_nmp_getVideoDevices()Lorg/bridj/Pointer;
    at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.__jprofiler_nmp_getVideoDevices(Native Method)
    at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.getVideoDevices(OpenIMAJGrabber.java)
    at com.github.sarxos.webcam.ds.buildin.cgt.GetDevicesTask.handle(GetDevicesTask.java:47)
    at com.github.sarxos.webcam.ds.buildin.WebcamGrabberProcessor$StaticProcessor.run(WebcamGrabberProcessor.java:108)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by mx1up** [comment]
in JProfiler, you can disable native method instrumentation:
![image](https://user-images.githubusercontent.com/178714/49747748-668aab00-fca4-11e8-8e1c-9eb0e52691a9.png)
