### ISSUE TITLE
Library 'OpenIMAJGrabber' was not loaded successfully

### ISSUE THREAD

**Issue by ANightCoder** [sarxos/webcam-capture#81]
@sarxos Hi !
When i use your webcam-capture, i meet a problem

```
java.lang.RuntimeException: Library 'OpenIMAJGrabber' was not loaded successfully from file 'C:\Users\USER\AppData\Local\Temp\BridJExtractedLibraries7239214121169806436\OpenIMAJGrabber.dll' 
at org.bridj.BridJ.getNativeLibrary(BridJ.java:952) 
at org.bridj.BridJ.getNativeLibrary(BridJ.java:931) 
at org.bridj.BridJ.getNativeLibrary(BridJ.java:543) 
at org.bridj.cpp.CPPRuntime.newCPPInstance(CPPRuntime.java:652) 
at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:858) 
at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:785) 
at org.bridj.CRuntime$CTypeInfo.initialize(CRuntime.java:249) 
at org.bridj.BridJ.initialize(BridJ.java:1000) 
at org.bridj.NativeObject.<init>(NativeObject.java:49) 
at org.bridj.StructObject.<init>(StructObject.java:44) 
at org.bridj.cpp.CPPObject.<init>(CPPObject.java:52) 
at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.<init>(OpenIMAJGrabber.java:64) 
at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.handle(WebcamDefaultDriver.java:56) 
at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:61) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 
at java.lang.Thread.run(Unknown Source) 
com.github.sarxos.webcam.WebcamException: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task 
```

Just the same problem like @hepin1989 https://github.com/ochafik/nativelibs4java/issues/364

And my OS is win7 ultimate
But, not all the win7 can not work ,just one of mine throw this exception, i don`t know why.
Could you help please ??

**Comment by jealfonso** [comment]
Despite I started the program with
 Webcam.setDriver(new LtiCivilDriver());
It continues stating that OpenIMAJGrabber was not loaded

Please help

**Comment by sarxos** [comment]
Hi @jealfonso,

Where are you setting `Webcam.setDriver(new LtiCivilDriver())`? This should be done immediately after you application is started. It won't change nothing if you get webcam first and then change driver. I also do not recommend using LTI-CIVIL. It's outdated technology and may not work on many newer operating systems. The last time when it was tested was at Windows XP.

On Windows you can try https://github.com/frankpapenmeier/webcam-capture-driver-native which works much better than default driver.

**Comment by shreshth01** [comment]
Hi sarxos,

I am still getting same error on windows 10 system when I trying to get WebCam.getDefault(). Can you please suggest something

**Comment by kkieffer** [comment]
FYI - it is working for me with the latest snapshot and Windows 10 with the built in driver (openimaj)

**Comment by kkieffer** [comment]
I am now starting to see this issue on some Windows computers, but not all.  I haven't been able to figure out why some computers have the issue and others don't.  Some sort of Windows security setting perhaps? Seen on Windows 8.1, Windows 11.

```
java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
	at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:124)

....
Caused by: java.lang.RuntimeException: Library 'OpenIMAJGrabber' was not loaded successfully from file 'C:\Users\info\AppData\Local\Temp\BridJExtractedLibraries7792404971508437487\OpenIMAJGrabber.dll'

```

**Comment by sderrien** [comment]
Hi @kkieffer, @sarxos 

I also have the same problem on two windows machine. Any clue of what could be the root cause of the problem ?

Thanks a lot,

Steven

**Comment by diveair** [comment]
I also get this issue after trying to git checkout the repo into Eclipse. I test the dev environment by exporting the unedited webcam-capture jar and then use it in an existing project (to test the dev environment before I edit the library) and I get the following printing to console Note the github jar file you can download for webcam-capture-0.3.12.jar works with my existing project just fine but upon Eclipse 09-2022 -> File -> Import -> Git -> Projects from Git (with smart import) -> Clone URI -> URI: https://github.com/sarxos/webcam-capture.git Host: github.com Repository path: /sarxos/webcam-capture.git Protocol: Https -> Branch: Master -> Select All -> Finish -> No visible errors -> then Eclipse -> Export -> Java -> JAR file -> Next -> webcam-capture_webcam-capture -> Finish and upon importing the jar into my working other project (in place of the one available at the repo) I get this error:

java.io.FileNotFoundException: Library 'OpenIMAJGrabber' was not found in path '[., C:/Program Files/Java/jre1.8.0_161/bin/server, C:/Program Files/Java/jre1.8.0_161/bin, C:/Program Files/Java/jre1.8.0_161/lib/amd64, C:\ProgramData\Oracle\Java\javapath, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0, C:\Windows\System32\OpenSSH, C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL, C:\Program Files\Intel\Intel(R) Management Engine Components\DAL, C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common, C:\WINDOWS\system32, C:\WINDOWS, C:\WINDOWS\System32\Wbem, C:\WINDOWS\System32\WindowsPowerShell\v1.0, C:\WINDOWS\System32\OpenSSH, C:\Program Files\Intel\WiFi\bin, C:\Program Files\Common Files\Intel\WirelessCommon, C:\Program Files (x86)\Schneider Electric\SoMachine Software\Tools\ConfigurationManager, C:\Program Files (x86)\QuickTime\QTSystem, C:\Program Files\Java\jdk1.8.0_161, C:\Program Files\Java\jdk1.8.0_161\bin, C:\Program Files\WorldPainter, C:\Program Files\TortoiseSVN\bin, C:\Program Files\dotnet, C:\Users\PC\AppData\Local\Microsoft\WindowsApps, C:\Users\PC\Desktop\eclipse, C:\Program Files\Java\jre1.8.0_161\bin, C:\WINDOWS\system32, C:\WINDOWS, C:/Program Files/Java/jre1.8.0_161/bin/server, C:/Program Files/Java/jre1.8.0_161/bin, C:/Program Files/Java/jre1.8.0_161/lib/amd64, C:\ProgramData\Oracle\Java\javapath, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0, C:\Windows\System32\OpenSSH, C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL, C:\Program Files\Intel\Intel(R) Management Engine Components\DAL, C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common, C:\WINDOWS\system32, C:\WINDOWS, C:\WINDOWS\System32\Wbem, C:\WINDOWS\System32\WindowsPowerShell\v1.0, C:\WINDOWS\System32\OpenSSH, C:\Program Files\Intel\WiFi\bin, C:\Program Files\Common Files\Intel\WirelessCommon, C:\Program Files (x86)\Schneider Electric\SoMachine Software\Tools\ConfigurationManager, C:\Program Files (x86)\QuickTime\QTSystem, C:\Program Files\Java\jdk1.8.0_161, C:\Program Files\Java\jdk1.8.0_161\bin, C:\Program Files\WorldPainter, C:\Program Files\TortoiseSVN\bin, C:\Program Files\dotnet, C:\Users\PC\AppData\Local\Microsoft\WindowsApps, C:\Users\PC\Desktop\eclipse, ., C:\Program Files\Java\jre1.8.0_161\bin, C:\Program Files\Java\jre1.8.0_161\bin]'
at org.bridj.BridJ.getNativeLibrary(BridJ.java:1074)
at org.bridj.BridJ.getNativeLibrary(BridJ.java:1049)
at org.bridj.BridJ.getNativeLibrary(BridJ.java:602)
at org.bridj.cpp.CPPRuntime.newCPPInstance(CPPRuntime.java:771)
at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:1022)
at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:904)
at org.bridj.CRuntime$CTypeInfo.initialize(CRuntime.java:271)
at org.bridj.BridJ.initialize(BridJ.java:1128)
at org.bridj.NativeObject.(NativeObject.java:50)
at org.bridj.StructObject.(StructObject.java:46)
at org.bridj.cpp.CPPObject.(CPPObject.java:55)
at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.(OpenIMAJGrabber.java:62)
at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.handle(WebcamDefaultDriver.java:55)
at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:81)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Exception in thread "main" com.github.sarxos.webcam.WebcamException: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:124)
at com.github.sarxos.webcam.Webcam.getWebcams(Webcam.java:893)
at com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:956)
at com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:933)
at com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:911)
at guitest.Widgets.WebcamWidget.(WebcamWidget.java:60)
at guitest.MainApp.main(MainApp.java:75)
Caused by: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
at java.util.concurrent.FutureTask.report(Unknown Source)
at java.util.concurrent.FutureTask.get(Unknown Source)
at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:116)
... 6 more
Caused by: com.github.sarxos.webcam.WebcamException: Cannot execute task
at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.process(WebcamProcessor.java:72)
at com.github.sarxos.webcam.WebcamProcessor.process(WebcamProcessor.java:140)
at com.github.sarxos.webcam.WebcamTask.process(WebcamTask.java:46)
at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.newGrabber(WebcamDefaultDriver.java:45)
at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver.getDevices(WebcamDefaultDriver.java:117)
at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:36)
at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:1)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Failed to allocate new instance of type class com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber
at org.bridj.cpp.CPPRuntime.newCPPInstance(CPPRuntime.java:812)
at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:1022)
at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:904)
at org.bridj.CRuntime$CTypeInfo.initialize(CRuntime.java:271)
at org.bridj.BridJ.initialize(BridJ.java:1128)
at org.bridj.NativeObject.(NativeObject.java:50)
at org.bridj.StructObject.(StructObject.java:46)
at org.bridj.cpp.CPPObject.(CPPObject.java:55)
at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.(OpenIMAJGrabber.java:62)
at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.handle(WebcamDefaultDriver.java:55)
at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:81)
... 3 more
Caused by: java.io.FileNotFoundException: Library 'OpenIMAJGrabber' was not found in path '[., C:/Program Files/Java/jre1.8.0_161/bin/server, C:/Program Files/Java/jre1.8.0_161/bin, C:/Program Files/Java/jre1.8.0_161/lib/amd64, C:\ProgramData\Oracle\Java\javapath, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0, C:\Windows\System32\OpenSSH, C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL, C:\Program Files\Intel\Intel(R) Management Engine Components\DAL, C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common, C:\WINDOWS\system32, C:\WINDOWS, C:\WINDOWS\System32\Wbem, C:\WINDOWS\System32\WindowsPowerShell\v1.0, C:\WINDOWS\System32\OpenSSH, C:\Program Files\Intel\WiFi\bin, C:\Program Files\Common Files\Intel\WirelessCommon, C:\Program Files (x86)\Schneider Electric\SoMachine Software\Tools\ConfigurationManager, C:\Program Files (x86)\QuickTime\QTSystem, C:\Program Files\Java\jdk1.8.0_161, C:\Program Files\Java\jdk1.8.0_161\bin, C:\Program Files\WorldPainter, C:\Program Files\TortoiseSVN\bin, C:\Program Files\dotnet, C:\Users\PC\AppData\Local\Microsoft\WindowsApps, C:\Users\PC\Desktop\eclipse, C:\Program Files\Java\jre1.8.0_161\bin, C:\WINDOWS\system32, C:\WINDOWS, C:/Program Files/Java/jre1.8.0_161/bin/server, C:/Program Files/Java/jre1.8.0_161/bin, C:/Program Files/Java/jre1.8.0_161/lib/amd64, C:\ProgramData\Oracle\Java\javapath, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0, C:\Windows\System32\OpenSSH, C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL, C:\Program Files\Intel\Intel(R) Management Engine Components\DAL, C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common, C:\WINDOWS\system32, C:\WINDOWS, C:\WINDOWS\System32\Wbem, C:\WINDOWS\System32\WindowsPowerShell\v1.0, C:\WINDOWS\System32\OpenSSH, C:\Program Files\Intel\WiFi\bin, C:\Program Files\Common Files\Intel\WirelessCommon, C:\Program Files (x86)\Schneider Electric\SoMachine Software\Tools\ConfigurationManager, C:\Program Files (x86)\QuickTime\QTSystem, C:\Program Files\Java\jdk1.8.0_161, C:\Program Files\Java\jdk1.8.0_161\bin, C:\Program Files\WorldPainter, C:\Program Files\TortoiseSVN\bin, C:\Program Files\dotnet, C:\Users\PC\AppData\Local\Microsoft\WindowsApps, C:\Users\PC\Desktop\eclipse, ., C:\Program Files\Java\jre1.8.0_161\bin, C:\Program Files\Java\jre1.8.0_161\bin]'
at org.bridj.BridJ.getNativeLibrary(BridJ.java:1074)
at org.bridj.BridJ.getNativeLibrary(BridJ.java:1049)
at org.bridj.BridJ.getNativeLibrary(BridJ.java:602)
at org.bridj.cpp.CPPRuntime.newCPPInstance(CPPRuntime.java:771)
... 13 more

BridJ: LoadLibrary error when loading OpenIMAJGrabber : The specified module could not be found.

**Comment by mtvgn** [comment]
So, no idea how this has happened, but here I am facing this same issue ...

I used to be working on this application (for a while now) working with a webcam on a MSI Katana laptop running Windows 10. Connecting to the camera worked there / then.
I got a (Dell) development laptop from the customer where I'm working for running Windows 11 and on that laptop the webcam works as well.
As the MSI Katana had issues I got another laptop from my boss, an HP with Windows 11, and the code runs fine there as well.
Now the customer where I'm working for came with a second "development Windows 11" laptop for another team member, it is also from Dell and seems the same as the one I'm using (although I cannot tell if Windows was installed in the exact same way / the exact same drivers are used, etc.), but somehow on this second development laptop the OpenIMAJGrabber.dll doesn't seem to be getting copied to the C:\Users\<user>\AppData\Local\Temp\BridJExtractedLibraries<number>\ directory after which the application will give a RuntimeException with the message Bridj can't find the OpenIMAJGrabber.dl in that Local Temp Bridj directory

Now, there are a couple of things I don't understand:
- on this second Dell development laptop, sometimes in the BridjExtractedLibrariues<number> folder there is a file called bridj.dll, sometimes there isn't. So maybe there's a timing issue with the Java code simply wanting to access the OpenIMAJGrabber.dll before it is written to that location?
- what I also found interesting is that on the HP laptop the OpenIMAJGrabber.dll would not (or not always) exist in the BridjExtractedLibrariues<number> directory, but the Java program would work with the camera nevertheless. So it also seems a copy of the dll in that specific location isn't always necessary

Looking at this thread I saw the message about some Microsoft Visual C++ libraries that could cause this problem, but that seems very unlikely in this case. Although it's also a bit annoying that this Dependency Walker that is being referenced is not working in Windows 11 anymore, so I cannot figure out easily if there's a dependency problem on this second Dell development laptop

@sarxos do you have any idea how to fix this problem?

**Comment by mtvgn** [comment]
For now I've gotten rid of the whole webcam-capture project in my project and have started using this: https://github.com/regwhitton/video-capture-inventory/ as that works on both development laptops

But I must say that the indexes of the used 'Logitech BRIO' and the 'Integrated webcam' are sometimes mixed up with the one I have to pass as parameter in the line `frameGrabber = new VideoInputFrameGrabber(index)`. For now I got it working on both machines by first sorting the devices `VideoCaptureInventory.get().getDevices()` comes up with by name and this way always getting the Logitech BRIO at index 1, but I don't know if that will always give the correct index / working. We'll have to sees
