### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by johnl5124** [sarxos/webcam-capture#850]
Hello, I'm in the process of integrating the webcam in my Raspberry Pi robotic project but I am having the error shown below and can't seem to get rid of it:

`
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at com.github.sarxos.webcam.Webcam.<clinit>(Webcam.java:101)
        at com.cam.testCam.main(testCam.java:13)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 2 more
`

After playing around with Jar files and the -classpath for ages I decided to start using Maven (which I am very new to) in an effort to keep my dependencies in check and hopefully get rid of my problems but with no luck. I was wondering if anyone could help me?

Thanks

**Comment by johnl5124** [comment]
### Update to my problem... now fixed
I stated I was new to using Maven and that showed. I was remoting into my Raspberry Pi and putting my own jar file there... without any of the dependencies. My assumption with Maven, was that once the jar file was created the dependencies were archived with it. This is not the case and after updating the POM file with the correct instructions, I got the dependencies to be archived along with my classes.

Below is what I added to fix my (simple) problem, may not be the best fix but it works. Unfortunately its a screenshot as GitHub doesn't seem to like including XML code via ctrl+e.
![image](https://user-images.githubusercontent.com/56348709/153470872-5ade5629-cb4c-4006-b043-ea09aa15b4ec.png)
