### ISSUE TITLE
maven project call webcam-capture fail on aarch64 platform

### ISSUE THREAD

**Issue by dshup** [sarxos/webcam-capture#878]
maven project call webcam-capture fail on aarch64 platform
get exceptions:

java.lang.RuntimeException: Failed to initialize BridJ (java.lang.UnsatisfiedLinkError: /tmp/BridJExtractedLibraries2069336107326078457/libbridj.so: /tmp/BridJExtractedLibraries2069336107326078457/libbridj.so: 无法打开共享对象文件: 没有那个文件或目录 (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform))
	at org.bridj.Platform.initLibrary(Platform.java:444)
at org.bridj.Platform.<clinit>(Platform.java:228)
	at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.<clinit>(OpenIMAJGrabber.java:59)
	at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.handle(WebcamDefaultDriver.java:55)
	at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:81)

Caused by: java.lang.UnsatisfiedLinkError: org.bridj.Platform.sizeOf_ptrdiff_t()I
	at org.bridj.Platform.sizeOf_ptrdiff_t(Native Method)
	at org.bridj.Platform.<clinit>(Platform.java:232)
	at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.<clinit>(OpenIMAJGrabber.java:59)
	at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.handle(WebcamDefaultDriver.java:55)
	at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:81)

my maven config:

`<dependency>
            <groupId>com.github.sarxos</groupId>
            <artifactId>webcam-capture</artifactId>
            <version>0.3.12</version>
        </dependency>

        <dependency>
            <groupId>com.nativelibs4java</groupId>
            <artifactId>bridj</artifactId>
            <version>0.7.0</version>
        </dependency>`

**Comment by dshup** [comment]
maven config:

        <dependency>
            <groupId>com.github.sarxos</groupId>
            <artifactId>webcam-capture</artifactId>
            <version>0.3.12</version>
        </dependency>

        <dependency>
            <groupId>com.nativelibs4java</groupId>
            <artifactId>bridj</artifactId>
            <version>0.7.0</version>
        </dependency>

**Comment by shinobisoft** [comment]
See this [https://github.com/sarxos/webcam-capture/issues/870#issuecomment-1210795046]()

**Comment by alexmao86** [comment]
offical OpenImaj does not include aarch64, i.e. arm64.

**Comment by dshup** [comment]
> offical OpenImaj does not include aarch64, i.e. arm64.

I got it, thank you! I already changed to use opencv
