### ISSUE TITLE
Webcam Record problem 

### ISSUE THREAD

**Issue by stefanmerfu** [sarxos/webcam-capture#88]
hello i meet this problem when i try to run file 

``` plain
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.UnsatisfiedLinkError: no xuggle-ferry in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
    at java.lang.Runtime.loadLibrary0(Runtime.java:845)
    at java.lang.System.loadLibrary(System.java:1084)
    at com.xuggle.ferry.JNILibraryLoader.loadLibrary0(JNILibraryLoader.java:265)
    at com.xuggle.ferry.JNILibraryLoader.loadLibrary(JNILibraryLoader.java:168)
    at com.xuggle.ferry.FerryJNI.<clinit>(FerryJNI.java:14)
    at com.xuggle.ferry.JNIMemoryManager.<clinit>(JNIMemoryManager.java:871)
    at com.xuggle.mediatool.MediaWriter.<clinit>(MediaWriter.java:119)
    at com.xuggle.mediatool.ToolFactory.makeWriter(ToolFactory.java:149)
    at com.github.sarxos.webcam.Encoder.main(Encoder.java:22)
Java Result: 1
BUILD SUCCESSFUL (total time: 0 seconds)
```

**Comment by afzaalhussain50** [comment]
hi, your webcam-capture api is outstanding , i am capturing video its working well, can you tell me that how i can capture video with audio recording??

Thanks

**Comment by khalilkhalili** [comment]
Hello Sarxos, 
I am using your API for capturing from AVerMedia DVD EZMaker 7 usb converter. The camera itself is NTSC compatible. Using your API, I capture images though it has huge amount of interlace.
Any solution you can propose ? It is much appreciated in advance. Thank you.
