### ISSUE TITLE
Big Sur 11.7.7, Library 'OpenIMAJGrabber' was not found in path

### ISSUE THREAD

**Issue by alders-lakes** [sarxos/webcam-capture#902]
Im using MacOS trying to take a picture and saving as a file, but I keep getting the message ```# BridJ: dlopen error when loading OpenIMAJGrabber : dlopen(OpenIMAJGrabber, 1): image not found``` with the error being ```Library 'OpenIMAJGrabber' was not found in path```

Heres the code, pom.xml, console error messages
```
package Camera;

import javax.imageio.ImageIO;
import java.io.File;
import java.io.IOException;

import com.github.sarxos.webcam.Webcam;

public class Main{
	public static void main(String[] args) {
		Webcam webcam = Webcam.getDefault();
		webcam.open();
		try {
			ImageIO.write(webcam.getImage(), "PNG", new File("hello-world.png"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
```
```<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>Camera</groupId>
  <artifactId>Camera</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  
  <build>
    <sourceDirectory>src</sourceDirectory>
    <resources>
      <resource>
        <directory>src</directory>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
    </resources>
    <plugins>
		
      <plugin>
		  
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <release>17</release>
        </configuration>
      </plugin>
    </plugins>
    
  </build>
    
    <dependencies>
		
		<!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-api -->
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-simple</artifactId>
    <version>2.0.7</version>
</dependency>
<dependency>
   <groupId>com.nativelibs4java</groupId>
   <artifactId>bridj</artifactId>
   <version>0.7.0</version>
</dependency>
<dependency>
  <groupId>com.github.sarxos</groupId>
  <artifactId>webcam-capture</artifactId>
  <version>0.3.12</version>
</dependency>
<!-- Thanks for using https://jar-download.com -->

    </dependencies>

</project>
```
```[main] INFO com.github.sarxos.webcam.Webcam - WebcamDefaultDriver capture driver will be used
java.io.FileNotFoundException: Library 'OpenIMAJGrabber' was not found in path '[., /usr/bin, /bin, /usr/sbin, /sbin, /Library/Java/Extensions, ., /Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.macosx.x86_64_17.0.6.v20230204-1729/jre/lib, /Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.macosx.x86_64_17.0.6.v20230204-1729/jre/bin, /usr/lib, /usr/local/lib]'
	at bridj@0.7.0/org.bridj.BridJ.getNativeLibrary(BridJ.java:1074)
	at bridj@0.7.0/org.bridj.BridJ.getNativeLibrary(BridJ.java:1049)
	at bridj@0.7.0/org.bridj.BridJ.getNativeLibrary(BridJ.java:602)
	at bridj@0.7.0/org.bridj.cpp.CPPRuntime.newCPPInstance(CPPRuntime.java:771)
	at bridj@0.7.0/org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:1022)
	at bridj@0.7.0/org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:904)
	at bridj@0.7.0/org.bridj.CRuntime$CTypeInfo.initialize(CRuntime.java:271)
	at bridj@0.7.0/org.bridj.BridJ.initialize(BridJ.java:1128)
	at bridj@0.7.0/org.bridj.NativeObject.<init>(NativeObject.java:50)
	at bridj@0.7.0/org.bridj.StructObject.<init>(StructObject.java:46)
	at bridj@0.7.0/org.bridj.cpp.CPPObject.<init>(CPPObject.java:55)
	at webcam.capture@0.3.13-20200330.202351-7/com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.<init>(OpenIMAJGrabber.java:62)
	at webcam.capture@0.3.13-20200330.202351-7/com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.handle(WebcamDefaultDriver.java:55)
	at webcam.capture@0.3.13-20200330.202351-7/com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:81)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "main" com.github.sarxos.webcam.WebcamException: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
	at webcam.capture@0.3.13-20200330.202351-7/com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:124)
	at webcam.capture@0.3.13-20200330.202351-7/com.github.sarxos.webcam.Webcam.getWebcams(Webcam.java:893)
	at webcam.capture@0.3.13-20200330.202351-7/com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:956)
	at webcam.capture@0.3.13-20200330.202351-7/com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:933)
	at webcam.capture@0.3.13-20200330.202351-7/com.github.sarxos.webcam.Webcam.getDefault(Webcam.java:911)
	at Camera/Camera.Main.main(Main.java:11)
Caused by: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at webcam.capture@0.3.13-20200330.202351-7/com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:116)
	... 5 more
Caused by: com.github.sarxos.webcam.WebcamException: Cannot execute task
	at webcam.capture@0.3.13-20200330.202351-7/com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.process(WebcamProcessor.java:72)
	at webcam.capture@0.3.13-20200330.202351-7/com.github.sarxos.webcam.WebcamProcessor.process(WebcamProcessor.java:140)
	at webcam.capture@0.3.13-20200330.202351-7/com.github.sarxos.webcam.WebcamTask.process(WebcamTask.java:46)
	at webcam.capture@0.3.13-20200330.202351-7/com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.newGrabber(WebcamDefaultDriver.java:45)
	at webcam.capture@0.3.13-20200330.202351-7/com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver.getDevices(WebcamDefaultDriver.java:117)
	at webcam.capture@0.3.13-20200330.202351-7/com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:36)
	at webcam.capture@0.3.13-20200330.202351-7/com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Failed to allocate new instance of type class com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber
	at bridj@0.7.0/org.bridj.cpp.CPPRuntime.newCPPInstance(CPPRuntime.java:812)
	at bridj@0.7.0/org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:1022)
	at bridj@0.7.0/org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:904)
	at bridj@0.7.0/org.bridj.CRuntime$CTypeInfo.initialize(CRuntime.java:271)
	at bridj@0.7.0/org.bridj.BridJ.initialize(BridJ.java:1128)
	at bridj@0.7.0/org.bridj.NativeObject.<init>(NativeObject.java:50)
	at bridj@0.7.0/org.bridj.StructObject.<init>(StructObject.java:46)
	at bridj@0.7.0/org.bridj.cpp.CPPObject.<init>(CPPObject.java:55)
	at webcam.capture@0.3.13-20200330.202351-7/com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.<init>(OpenIMAJGrabber.java:62)
	at webcam.capture@0.3.13-20200330.202351-7/com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.handle(WebcamDefaultDriver.java:55)
	at webcam.capture@0.3.13-20200330.202351-7/com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:81)
	... 3 more
Caused by: java.io.FileNotFoundException: Library 'OpenIMAJGrabber' was not found in path '[., /usr/bin, /bin, /usr/sbin, /sbin, /Library/Java/Extensions, ., /Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.macosx.x86_64_17.0.6.v20230204-1729/jre/lib, /Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.macosx.x86_64_17.0.6.v20230204-1729/jre/bin, /usr/lib, /usr/local/lib]'
	at bridj@0.7.0/org.bridj.BridJ.getNativeLibrary(BridJ.java:1074)
	at bridj@0.7.0/org.bridj.BridJ.getNativeLibrary(BridJ.java:1049)
	at bridj@0.7.0/org.bridj.BridJ.getNativeLibrary(BridJ.java:602)
	at bridj@0.7.0/org.bridj.cpp.CPPRuntime.newCPPInstance(CPPRuntime.java:771)
	... 13 more
# BridJ: dlopen error when loading OpenIMAJGrabber : dlopen(OpenIMAJGrabber, 1): image not found
# BridJ: dlopen error when loading OpenIMAJGrabber : dlopen(OpenIMAJGrabber, 1): image not found
# BridJ: dlopen error when loading OpenIMAJGrabber : dlopen(OpenIMAJGrabber, 1): image not found
# BridJ: dlopen error when loading OpenIMAJGrabber : dlopen(OpenIMAJGrabber, 1): image not found
# BridJ: dlopen error when loading OpenIMAJGrabber : dlopen(OpenIMAJGrabber, 1): image not found
# BridJ: dlopen error when loading OpenIMAJGrabber : dlopen(OpenIMAJGrabber, 1): image not found
# BridJ: dlopen error when loading OpenIMAJGrabber : dlopen(OpenIMAJGrabber, 1): image not found
# BridJ: dlopen error when loading OpenIMAJGrabber : dlopen(OpenIMAJGrabber, 1): image not found
# BridJ: dlopen error when loading OpenIMAJGrabber : dlopen(OpenIMAJGrabber, 1): image not found
# BridJ: dlopen error when loading OpenIMAJGrabber : dlopen(OpenIMAJGrabber, 1): image not found
# BridJ: dlopen error when loading OpenIMAJGrabber : dlopen(OpenIMAJGrabber, 1): image not found
```

**Comment by alders-lakes** [comment]
Only worked on my windows computer :(
